import assert from 'node:assert/strict';
import test from 'node:test';
import { ChatGptSubscriptionProvider } from './chatgpt-provider.ts';
import { AiProviderFailure } from './provider.ts';

const task={operation:'generate' as const,purpose:'synthetic_test',input:'Synthetic input',modelTier:'routine' as const,sources:[]};
const config={provider:'chatgpt_subscription' as const,model:'gpt-6.1-sol',apiKey:'synthetic-oauth-token'};
function stream(...events:unknown[]){return new Response(events.map((event)=>`event: ${(event as any).type}\r\ndata: ${JSON.stringify(event)}\r\n\r\n`).join(''),{status:200,headers:{'content-type':'text/event-stream'}});}

test('ChatGPT plan adapter uses the public streaming contract and accepts only completed',async()=>{let body:any;const provider=new ChatGptSubscriptionProvider(async(_url,init)=>{body=JSON.parse(String(init.body));return stream({type:'response.completed',response:{status:'completed',model:'gpt-6.1-sol-actual',service_tier:'standard',output:[{type:'message',content:[{type:'output_text',text:'OK'}]}],usage:{input_tokens:12,output_tokens:7,input_tokens_details:{cached_tokens:3,cache_write_tokens:2},output_tokens_details:{reasoning_tokens:4}}}});});const result=await provider.execute(task,config);assert.equal(result.output,'OK');assert.equal(result.actualModel,'gpt-6.1-sol-actual');assert.equal(result.actualServiceTier,'standard');assert.deepEqual(result.usage,{inputTokens:12,outputTokens:7,cachedInputTokens:3,cacheWriteTokens:2,reasoningTokens:4});assert.equal(body.stream,true);assert.equal(body.store,false);for(const forbidden of ['max_output_tokens','background','previous_response_id','conversation','metadata'])assert.equal(forbidden in body,false);});

test('ChatGPT plan tools are namespaced and full output history precedes local tool results',async()=>{const bodies:any[]=[];const provider=new ChatGptSubscriptionProvider(async(_url,init)=>{const body=JSON.parse(String(init.body));bodies.push(body);if(bodies.length===1)return stream({type:'response.completed',response:{status:'completed',output:[{type:'function_call',call_id:'call_1',name:body.tools[0].tools[0].name,arguments:'{"value":"x"}'}]}});return stream({type:'response.completed',response:{status:'completed',output:[{type:'message',content:[{type:'output_text',text:'done'}]}]}});});const session=provider.createSession(task,config,[{name:'web.open',description:'Open an approved URL',inputSchema:{type:'object'}}]);const first=await session.next([], 'required');assert.equal(first.toolCalls[0]?.name,'web.open');const second=await session.next([{callId:'call_1',name:'web.open',output:'synthetic'}]);assert.equal(second.output,'done');assert.equal(bodies[0].tools[0].type,'namespace');assert.equal(bodies[0].tools[0].name,'samvev');assert.ok(bodies[1].input.some((item:any)=>item.type==='function_call'));assert.ok(bodies[1].input.some((item:any)=>item.type==='function_call_output'));session.close();});

for(const [name,event,code] of [
  ['failed',{type:'response.failed',response:{error:{code:'subscription_sharing_usage_limit_exceeded'}}},'AI_PLAN_USAGE_LIMITED'],
  ['not eligible',{type:'response.failed',response:{error:{code:'subscription_sharing_user_not_eligible'}}},'AI_PLAN_NOT_ELIGIBLE'],
  ['missing permission',{type:'response.failed',response:{error:{code:'chatpass_v2_scope_not_authorized'}}},'AI_PLAN_PERMISSION_REQUIRED'],
  ['invalid authorization context',{type:'response.failed',response:{error:{code:'chatpass_v2_invalid_authorization_context'}}},'AI_REAUTHORIZATION_REQUIRED'],
  ['incomplete',{type:'response.incomplete',response:{incomplete_details:{reason:'limit'}}},'AI_UPSTREAM_ERROR']
] as const)test(`ChatGPT plan ${name} stream never publishes success`,async()=>{const provider=new ChatGptSubscriptionProvider(async()=>stream(event));await assert.rejects(()=>provider.execute(task,config),(error:any)=>error instanceof AiProviderFailure&&error.code===code);});

test('ChatGPT plan broken stream is an explicit interrupted attempt',async()=>{const provider=new ChatGptSubscriptionProvider(async()=>stream({type:'response.output_text.delta',delta:'partial'}));await assert.rejects(()=>provider.execute(task,config),(error:any)=>error instanceof AiProviderFailure&&error.code==='AI_STREAM_INTERRUPTED');});

test('terminal failures retain reported model tier and billable usage without substituting the request alias',async()=>{const provider=new ChatGptSubscriptionProvider(async()=>stream({type:'response.failed',response:{status:'failed',model:'gpt-6.1-sol',service_tier:'standard',error:{code:'subscription_sharing_usage_unavailable'},usage:{input_tokens:100,output_tokens:20,input_tokens_details:{cached_tokens:10,cache_write_tokens:5},output_tokens_details:{reasoning_tokens:4}}}}));await assert.rejects(()=>provider.execute(task,{...config,model:'requested-alias'}),(error:any)=>error instanceof AiProviderFailure&&error.code==='AI_PROVIDER_UNAVAILABLE'&&error.actualModel==='gpt-6.1-sol'&&error.actualServiceTier==='standard'&&error.usage?.cachedInputTokens===10&&error.usage?.cacheWriteTokens===5);});

test('an already-aborted request never reaches beforeDispatch or the wire',async()=>{let wire=0,dispatch=0;const provider=new ChatGptSubscriptionProvider(async()=>{wire++;return stream();});const controller=new AbortController();controller.abort();const session=provider.createSession(task,{...config,beforeDispatch:async()=>{dispatch++;}},[],controller.signal);await assert.rejects(()=>session.next(),(error:any)=>error instanceof AiProviderFailure&&error.code==='AI_TIMEOUT');assert.equal(dispatch,0);assert.equal(wire,0);session.close();});

test('an abort while final authorization is awaiting never marks or starts the wire',async()=>{let wire=0,wireStarts=0;let release!:()=>void;const gate=new Promise<void>((resolve)=>{release=resolve;});const provider=new ChatGptSubscriptionProvider(async()=>{wire++;return stream();});const controller=new AbortController();const session=provider.createSession(task,{...config,beforeDispatch:async()=>{controller.abort();await gate;},onWireStart:()=>{wireStarts++;}},[],controller.signal);const result=session.next();release();await assert.rejects(result,(error:any)=>error instanceof AiProviderFailure&&error.code==='AI_TIMEOUT');assert.equal(wireStarts,0);assert.equal(wire,0);session.close();});
