import assert from 'node:assert/strict';
import test from 'node:test';
import { generateKeyPairSync,sign } from 'node:crypto';
import { validateOpenAiAccessToken,validateOpenAiIdToken } from './chatgpt-oauth.ts';

const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});const jwk=publicKey.export({format:'jwk'});Object.assign(jwk,{kid:'synthetic-key',use:'sig',alg:'RS256'});
function jwt(payload:Record<string,unknown>){const header=Buffer.from(JSON.stringify({alg:'RS256',kid:'synthetic-key'})).toString('base64url');const body=Buffer.from(JSON.stringify(payload)).toString('base64url');return`${header}.${body}.${sign('RSA-SHA256',Buffer.from(`${header}.${body}`),privateKey).toString('base64url')}`;}
const transport=async(url:string)=>url.endsWith('openid-configuration')?new Response(JSON.stringify({issuer:'https://auth.openai.com',jwks_uri:'https://auth.openai.com/.well-known/jwks.json'}),{status:200}):new Response(JSON.stringify({keys:[jwk]}),{status:200});
const now=Math.floor(Date.now()/1000);

test('OIDC validation binds signature issuer audience client subject expiry nonce and signed time bounds',async()=>{const id=jwt({iss:'https://auth.openai.com',aud:'oaiapp_synthetic',sub:'subject-1',nonce:'nonce-1',email:'owner@example.invalid',iat:now,nbf:now-1,exp:now+600});assert.deepEqual(await validateOpenAiIdToken(id,'oaiapp_synthetic',transport,'nonce-1'),{issuer:'https://auth.openai.com',subject:'subject-1',email:'owner@example.invalid'});for(const [client,nonce] of [['wrong','nonce-1'],['oaiapp_synthetic','wrong']] as const)await assert.rejects(()=>validateOpenAiIdToken(id,client,transport,nonce));await assert.rejects(()=>validateOpenAiIdToken(jwt({iss:'https://auth.openai.com',aud:'oaiapp_synthetic',sub:'subject-1',nonce:'nonce-1',exp:now-1}),'oaiapp_synthetic',transport,'nonce-1'));await assert.rejects(()=>validateOpenAiIdToken(jwt({iss:'https://auth.openai.com',aud:'oaiapp_synthetic',sub:'subject-1',nonce:'nonce-1',nbf:now+600,exp:now+1200}),'oaiapp_synthetic',transport,'nonce-1'));await assert.rejects(()=>validateOpenAiIdToken(jwt({iss:'https://auth.openai.com',aud:'oaiapp_synthetic',sub:'subject-1',nonce:'nonce-1',iat:now+600,exp:now+1200}),'oaiapp_synthetic',transport,'nonce-1'));});

test('access token validation derives granted scopes from signed claims',async()=>{const token=jwt({iss:'https://auth.openai.com',aud:'https://api.openai.com/v1',client_id:'oaiapp_synthetic',sub:'subject-1',scope:'openid profile email offline_access resource.invoke chatgpt.tokens.use.direct',exp:now+600});const result=await validateOpenAiAccessToken(token,'oaiapp_synthetic','subject-1',transport);assert.ok(result.scopes.includes('chatgpt.tokens.use.direct'));await assert.rejects(()=>validateOpenAiAccessToken(jwt({iss:'https://auth.openai.com',aud:'https://api.openai.com/v1',client_id:'oaiapp_synthetic',sub:'subject-1',scope:'openid profile email',exp:now+600}),'oaiapp_synthetic','subject-1',transport));});
