import { createPublicKey, randomUUID, verify } from 'node:crypto';
import { aiChatGptCredentialRecordSchema, type AiProviderId } from '@samvev/contracts';
import { DomainError } from '@samvev/core';
import { pool, transaction, type DbClient } from '../db.ts';
import { AiCredentialVault } from './credential-vault.ts';
import type { AiHttpTransport } from './openai-provider.ts';

const ISSUER='https://auth.openai.com';
const RESOURCE='https://api.openai.com/v1';
const TOKEN_URL='https://auth.openai.com/api/accounts/oauth/token';
const MODELS_URL='https://api.openai.com/v1/models';
const REQUIRED_SCOPES=['openid','profile','email','offline_access','resource.invoke','chatgpt.tokens.use.direct'];

interface Actor{householdId:string;installationId:string;accountId:string;membershipId:string;}
interface CredentialBundle{idToken:string;accessToken:string;refreshToken:string;tokenType:'Bearer';expiresAt:string;savedAt:string;earliestRefreshAt?:string;}
interface RegistrationRow{id:string;household_id:string;owner_account_id:string;owner_membership_id:string;label:string;issuer:string;subject:string;email:string|null;issued_client_id:string;granted_scopes:string[];credential_ciphertext:string|null;access_expires_at:Date|null;status:string;generation:number;revision:number;last_error_code:string|null;}

function object(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function tokenTimesValid(payload:Record<string,unknown>):boolean{const now=Math.floor(Date.now()/1000);return typeof payload.exp==='number'&&payload.exp>now&&(payload.nbf===undefined||(typeof payload.nbf==='number'&&payload.nbf<=now+60&&payload.nbf<=payload.exp))&&(payload.iat===undefined||(typeof payload.iat==='number'&&payload.iat<=now+300&&payload.iat<=payload.exp));}
function earliestRefreshAt(value:unknown):string|undefined{if(value===undefined||value===null)return undefined;const date=typeof value==='number'&&Number.isFinite(value)?new Date(value*1000):typeof value==='string'?new Date(value):new Date(Number.NaN);if(Number.isNaN(date.getTime()))throw new DomainError('AI_CONFIGURATION_INVALID',422,{reason:'invalid_earliest_refresh_at'});return date.toISOString();}
function base64Json(value:string):Record<string,unknown>{try{const parsed=JSON.parse(Buffer.from(value,'base64url').toString('utf8'));if(object(parsed))return parsed;}catch{}throw new DomainError('AI_CONFIGURATION_INVALID',422,{reason:'invalid_id_token'});}
async function responseJson(response:Response,maxBytes=512*1024):Promise<unknown>{const text=await response.text();if(Buffer.byteLength(text)>maxBytes)throw new DomainError('AI_PROVIDER_UNAVAILABLE',502);try{return JSON.parse(text);}catch{throw new DomainError('AI_PROVIDER_UNAVAILABLE',502);}}
async function boundedJson(response:Response,maxBytes=512*1024):Promise<unknown>{if(!response.ok)throw new DomainError('AI_PROVIDER_UNAVAILABLE',502);return responseJson(response,maxBytes);}

export interface ValidatedIdentity{issuer:string;subject:string;email?:string;}
export async function validateOpenAiIdToken(idToken:string,clientId:string,transport:AiHttpTransport=fetch,expectedNonce?:string):Promise<ValidatedIdentity>{
  const parts=idToken.split('.');if(parts.length!==3)throw new DomainError('AI_CONFIGURATION_INVALID',422,{reason:'invalid_id_token'});
  const header=base64Json(parts[0]!);const payload=base64Json(parts[1]!);
  if(header.alg!=='RS256'||typeof header.kid!=='string')throw new DomainError('AI_CONFIGURATION_INVALID',422,{reason:'unsupported_id_token'});
  const discoveryResponse=await transport(`${ISSUER}/.well-known/openid-configuration`,{headers:{accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(10_000)});
  const discovery=await boundedJson(discoveryResponse);
  if(!object(discovery)||discovery.issuer!==ISSUER||typeof discovery.jwks_uri!=='string'||!discovery.jwks_uri.startsWith(`${ISSUER}/`))throw new DomainError('AI_CONFIGURATION_INVALID',502,{reason:'invalid_oidc_discovery'});
  const jwksResponse=await transport(discovery.jwks_uri,{headers:{accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(10_000)});
  const jwks=await boundedJson(jwksResponse);const keys=object(jwks)&&Array.isArray(jwks.keys)?jwks.keys:[];const jwk=keys.find((key)=>object(key)&&key.kid===header.kid&&key.kty==='RSA');
  if(!object(jwk))throw new DomainError('AI_CONFIGURATION_INVALID',422,{reason:'id_token_key_not_found'});
  let valid=false;try{valid=verify('RSA-SHA256',Buffer.from(`${parts[0]}.${parts[1]}`),createPublicKey({key:jwk as any,format:'jwk'}),Buffer.from(parts[2]!,'base64url'));}catch{}
  const audiences=typeof payload.aud==='string'?[payload.aud]:Array.isArray(payload.aud)?payload.aud:[];
  if(!valid||payload.iss!==ISSUER||!audiences.includes(clientId)||!tokenTimesValid(payload)||typeof payload.sub!=='string'||(expectedNonce!==undefined&&payload.nonce!==expectedNonce))throw new DomainError('AI_CONFIGURATION_INVALID',422,{reason:'id_token_validation_failed'});
  return{issuer:ISSUER,subject:payload.sub,...(typeof payload.email==='string'?{email:payload.email}:{})};
}

export async function validateOpenAiAccessToken(accessToken:string,clientId:string,subject:string,transport:AiHttpTransport=fetch):Promise<{scopes:string[];expiresAt:string}>{
  const parts=accessToken.split('.');if(parts.length!==3)throw new DomainError('AI_CONFIGURATION_INVALID',422,{reason:'invalid_access_token'});const header=base64Json(parts[0]!);const payload=base64Json(parts[1]!);if(header.alg!=='RS256'||typeof header.kid!=='string')throw new DomainError('AI_CONFIGURATION_INVALID',422,{reason:'unsupported_access_token'});
  const discovery=await boundedJson(await transport(`${ISSUER}/.well-known/openid-configuration`,{headers:{accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(10_000)}));if(!object(discovery)||discovery.issuer!==ISSUER||typeof discovery.jwks_uri!=='string'||!discovery.jwks_uri.startsWith(`${ISSUER}/`))throw new DomainError('AI_CONFIGURATION_INVALID',502);const jwks=await boundedJson(await transport(discovery.jwks_uri,{headers:{accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(10_000)}));const jwk=object(jwks)&&Array.isArray(jwks.keys)?jwks.keys.find((key)=>object(key)&&key.kid===header.kid&&key.kty==='RSA'):undefined;let valid=false;try{valid=Boolean(jwk)&&verify('RSA-SHA256',Buffer.from(`${parts[0]}.${parts[1]}`),createPublicKey({key:jwk as any,format:'jwk'}),Buffer.from(parts[2]!,'base64url'));}catch{}
  const audiences=typeof payload.aud==='string'?[payload.aud]:Array.isArray(payload.aud)?payload.aud:[];const tokenClient=payload.client_id??payload.azp;const scopes=typeof payload.scope==='string'?payload.scope.split(/\s+/).filter(Boolean):Array.isArray(payload.scopes)?payload.scopes.filter((item):item is string=>typeof item==='string'):[];
  if(!valid||payload.iss!==ISSUER||!audiences.includes(RESOURCE)||tokenClient!==clientId||payload.sub!==subject||!tokenTimesValid(payload)||!REQUIRED_SCOPES.every((scope)=>scopes.includes(scope)))throw new DomainError('AI_CONFIGURATION_INVALID',422,{reason:'access_token_validation_failed'});return{scopes:[...new Set(scopes)].sort(),expiresAt:new Date((payload.exp as number)*1000).toISOString()};
}

function safeRegistration(row:RegistrationRow,actor:Actor){const owner=row.owner_account_id===actor.accountId;return{id:row.id,label:owner?row.label:'ChatGPT connection',status:row.status,revision:row.revision,isOwner:owner,canManage:owner,...(owner?{email:row.email,subjectSuffix:row.subject.slice(-8),scopes:row.granted_scopes,expiresAt:row.access_expires_at?.toISOString()??null,ownerAccountId:actor.accountId,errorCode:row.last_error_code}:{})};}

export class ChatGptOAuthService{
  private vault:AiCredentialVault;
  constructor(private transport:AiHttpTransport=fetch,keyFile?:string){this.vault=new AiCredentialVault(keyFile);}
  async hostId(installationId:string):Promise<string>{const value=`urn:uuid:${randomUUID()}`;return(await pool.query<{ext_agent_host_id:string}>(`INSERT INTO ai_runtime_hosts(installation_id,ext_agent_host_id) VALUES($1,$2) ON CONFLICT(installation_id) DO UPDATE SET ext_agent_host_id=ai_runtime_hosts.ext_agent_host_id RETURNING ext_agent_host_id`,[installationId,value])).rows[0]!.ext_agent_host_id;}
  async list(actor:Actor){const hostId=await this.hostId(actor.installationId);const rows=await pool.query<RegistrationRow>('SELECT * FROM ai_chatgpt_registrations WHERE household_id=$1 ORDER BY created_at,id',[actor.householdId]);const active=(await pool.query<{active_chatgpt_registration_id:string|null}>('SELECT active_chatgpt_registration_id FROM ai_settings WHERE household_id=$1',[actor.householdId])).rows[0]?.active_chatgpt_registration_id??null;return{hostId,activeRegistrationId:active,registrations:rows.rows.map((row)=>safeRegistration(row,actor)),usageUrl:'https://chatgpt.com/settings/usage',companionCommand:`npm run ai:chatgpt-connect -- --host-id '${hostId}' --output /path/to/samvev-chatgpt-credential.json`,importMethod:'secure_copy_then_cli',importCommand:'npm run ai:chatgpt-import -- --household <id> --file <credential.json>',acceptsBrowserTokenPaste:false};}
  async import(actor:Actor,raw:unknown,expectedRevision:number){await this.hostId(actor.installationId);const credential=aiChatGptCredentialRecordSchema.parse(raw);const identity=await validateOpenAiIdToken(credential.idToken,credential.clientId,this.transport);if(identity.subject!==credential.subject||identity.issuer!==credential.issuer||(credential.email&&identity.email&&credential.email!==identity.email))throw new DomainError('AI_CONFIGURATION_INVALID',422,{reason:'credential_identity_mismatch'});
    const access=await validateOpenAiAccessToken(credential.accessToken,credential.clientId,identity.subject,this.transport);const scopes=access.scopes;
    const bundle:CredentialBundle={idToken:credential.idToken,accessToken:credential.accessToken,refreshToken:credential.refreshToken,tokenType:'Bearer',expiresAt:access.expiresAt,savedAt:credential.savedAt,...(credential.earliestRefreshAt?{earliestRefreshAt:credential.earliestRefreshAt}:{})};
    return transaction(async(client)=>{let settings=(await client.query<{revision:number}>('SELECT revision FROM ai_settings WHERE household_id=$1 FOR UPDATE',[actor.householdId])).rows[0];if(!settings){if(expectedRevision!==0)throw new DomainError('REVISION_CONFLICT',409);await client.query(`INSERT INTO ai_settings(household_id) VALUES($1) ON CONFLICT DO NOTHING`,[actor.householdId]);settings={revision:0};}if(settings.revision!==expectedRevision)throw new DomainError('REVISION_CONFLICT',409);
      const existing=(await client.query<{id:string}>('SELECT id FROM ai_chatgpt_registrations WHERE household_id=$1 AND owner_account_id=$2 AND issuer=$3 AND subject=$4 AND issued_client_id=$5 FOR UPDATE',[actor.householdId,actor.accountId,identity.issuer,identity.subject,credential.clientId])).rows[0];const registrationId=existing?.id??randomUUID();const ciphertext=await this.vault.encrypt(`${actor.householdId}:${registrationId}`,JSON.stringify(bundle));
      const row=(await client.query<RegistrationRow>(`INSERT INTO ai_chatgpt_registrations(id,household_id,owner_account_id,owner_membership_id,label,issuer,subject,email,issued_client_id,granted_scopes,credential_ciphertext,access_expires_at,status)
        VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'connected') ON CONFLICT(household_id,owner_account_id,issuer,subject,issued_client_id) DO UPDATE SET label=EXCLUDED.label,email=EXCLUDED.email,owner_membership_id=EXCLUDED.owner_membership_id,granted_scopes=EXCLUDED.granted_scopes,credential_ciphertext=EXCLUDED.credential_ciphertext,access_expires_at=EXCLUDED.access_expires_at,status='connected',last_error_code=NULL,generation=ai_chatgpt_registrations.generation+1,revision=ai_chatgpt_registrations.revision+1,updated_at=clock_timestamp() RETURNING *`,[registrationId,actor.householdId,actor.accountId,actor.membershipId,credential.label,identity.issuer,identity.subject,identity.email??credential.email??null,credential.clientId,scopes,ciphertext,access.expiresAt])).rows[0]!;
      await client.query(`UPDATE ai_settings SET active_chatgpt_registration_id=$2,revision=revision+1,availability_status='not_tested',availability_error_code=NULL,availability_checked_at=NULL,availability_checked_revision=NULL,updated_at=clock_timestamp() WHERE household_id=$1`,[actor.householdId,row.id]);return safeRegistration(row,actor);});
  }
  async accessToken(actor:Actor,registrationId:string):Promise<{token:string;generation:number;clientId:string}>{const result=await transaction(async(client)=>{await client.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[registrationId]);const row=(await client.query<RegistrationRow>(`SELECT r.* FROM ai_chatgpt_registrations r JOIN accounts a ON a.id=r.owner_account_id AND a.disabled_at IS NULL JOIN memberships m ON m.id=r.owner_membership_id AND m.account_id=r.owner_account_id AND m.household_id=r.household_id AND m.capabilities ? 'household.manage' WHERE r.id=$1 AND r.household_id=$2 FOR UPDATE OF r`,[registrationId,actor.householdId])).rows[0];if(!row||row.owner_account_id!==actor.accountId||row.owner_membership_id!==actor.membershipId)throw new DomainError('FORBIDDEN',403);if(row.status==='usage_limited')throw new DomainError('AI_PLAN_USAGE_LIMITED',422);if(row.status==='not_eligible')throw new DomainError('AI_PLAN_NOT_ELIGIBLE',422);if(row.status==='reauthorization_required'&&['missing_required_scope','AI_PLAN_PERMISSION_REQUIRED'].includes(row.last_error_code??''))throw new DomainError('AI_PLAN_PERMISSION_REQUIRED',422);if(!row.credential_ciphertext||row.status!=='connected')throw new DomainError('AI_REAUTHORIZATION_REQUIRED',422);
      let bundle:CredentialBundle;try{bundle=JSON.parse(await this.vault.decrypt(`${actor.householdId}:${row.id}`,row.credential_ciphertext)) as CredentialBundle;}catch{throw new DomainError('AI_CONFIGURATION_INVALID',422);}
      if(new Date(bundle.expiresAt).getTime()>Date.now()+120_000)return{token:bundle.accessToken,generation:row.generation,clientId:row.issued_client_id};
      if(bundle.earliestRefreshAt&&new Date(bundle.earliestRefreshAt).getTime()>Date.now()){if(new Date(bundle.expiresAt).getTime()>Date.now())return{token:bundle.accessToken,generation:row.generation,clientId:row.issued_client_id};return{failure:'AI_PROVIDER_UNAVAILABLE' as const,reason:'refresh_not_yet_allowed'};}
      const response=await this.transport(TOKEN_URL,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:row.issued_client_id,refresh_token:bundle.refreshToken,resource:RESOURCE}),redirect:'error',signal:AbortSignal.timeout(10_000)});let value:unknown;try{value=await responseJson(response);}catch{value={};}
      if(!response.ok||!object(value)||typeof value.access_token!=='string'||typeof value.refresh_token!=='string'||typeof value.expires_in!=='number'){const error=object(value)&&typeof value.error==='string'?value.error:'refresh_failed';const terminal=['invalid_grant','invalid_refresh_token','token_expired','refresh_token_expired','refresh_token_invalidated','refresh_token_reused'].includes(error);if(terminal)await client.query(`UPDATE ai_chatgpt_registrations SET credential_ciphertext=NULL,status='reauthorization_required',last_error_code=$3,generation=generation+1,revision=revision+1,updated_at=clock_timestamp() WHERE id=$1 AND household_id=$2`,[row.id,actor.householdId,error]);return{failure:(terminal?'AI_REAUTHORIZATION_REQUIRED':'AI_PROVIDER_UNAVAILABLE') as 'AI_REAUTHORIZATION_REQUIRED'|'AI_PROVIDER_UNAVAILABLE',reason:error};}
      const accessToken=value.access_token as string;const refreshToken=value.refresh_token as string;const scopes=typeof value.scope==='string'?value.scope.split(/\s+/).filter(Boolean):[];if(!REQUIRED_SCOPES.every((scope)=>scopes.includes(scope))){await client.query(`UPDATE ai_chatgpt_registrations SET credential_ciphertext=NULL,status='reauthorization_required',last_error_code='missing_required_scope',generation=generation+1,revision=revision+1,updated_at=clock_timestamp() WHERE id=$1`,[row.id]);return{failure:'AI_PLAN_PERMISSION_REQUIRED' as const,reason:'missing_required_scope'};}
      try{const verified=await validateOpenAiAccessToken(accessToken,row.issued_client_id,row.subject,this.transport);if(typeof value.id_token==='string'){const identity=await validateOpenAiIdToken(value.id_token,row.issued_client_id,this.transport);if(identity.subject!==row.subject||identity.issuer!==row.issuer)throw new DomainError('AI_CONFIGURATION_INVALID',422);}const refreshFloor=earliestRefreshAt(value.earliest_refresh_at);const next:CredentialBundle={...bundle,accessToken,refreshToken,expiresAt:verified.expiresAt,savedAt:new Date().toISOString(),...(refreshFloor?{earliestRefreshAt:refreshFloor}:{}),...(typeof value.id_token==='string'?{idToken:value.id_token}:{})};const encrypted=await this.vault.encrypt(`${actor.householdId}:${row.id}`,JSON.stringify(next));const updated=(await client.query<{generation:number}>(`UPDATE ai_chatgpt_registrations SET credential_ciphertext=$3,access_expires_at=$4,granted_scopes=$5,revision=revision+1,status='connected',last_error_code=NULL,updated_at=clock_timestamp() WHERE id=$1 AND household_id=$2 RETURNING generation`,[row.id,actor.householdId,encrypted,next.expiresAt,scopes])).rows[0]!;return{token:next.accessToken,generation:updated.generation,clientId:row.issued_client_id};}catch{await client.query(`UPDATE ai_chatgpt_registrations SET credential_ciphertext=NULL,status='reauthorization_required',last_error_code='refresh_validation_failed',generation=generation+1,revision=revision+1,updated_at=clock_timestamp() WHERE id=$1`,[row.id]);return{failure:'AI_REAUTHORIZATION_REQUIRED' as const,reason:'refresh_validation_failed'};}});if('failure' in result&&result.failure)throw new DomainError(result.failure,result.failure==='AI_PROVIDER_UNAVAILABLE'?502:422,{reason:result.reason??'refresh_failed'});return result;}
  async models(actor:Actor,registrationId:string){const access=await this.accessToken(actor,registrationId);const response=await this.transport(MODELS_URL,{headers:{authorization:`Bearer ${access.token}`,accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(10_000)});if(!response.ok)throw new DomainError('AI_PROVIDER_UNAVAILABLE',502);const text=await response.text();if(Buffer.byteLength(text)>512*1024)throw new DomainError('AI_PROVIDER_UNAVAILABLE',502);let value:unknown;try{value=JSON.parse(text);}catch{throw new DomainError('AI_PROVIDER_UNAVAILABLE',502);}const source=object(value)&&Array.isArray(value.models)?value.models:[];const models=source.filter((item)=>object(item)&&item.visibility==='list'&&typeof item.slug==='string'&&typeof item.display_name==='string').map((item,index)=>({slug:item.slug as string,displayName:item.display_name as string,position:index}));await transaction(async(client)=>{const current=(await client.query<RegistrationRow>('SELECT * FROM ai_chatgpt_registrations WHERE id=$1 AND household_id=$2 FOR UPDATE',[registrationId,actor.householdId])).rows[0];if(!current||current.owner_account_id!==actor.accountId||current.status!=='connected'||current.generation!==access.generation)throw new DomainError('AI_REAUTHORIZATION_REQUIRED',422);await client.query('DELETE FROM ai_chatgpt_models WHERE registration_id=$1',[registrationId]);for(const model of models)await client.query('INSERT INTO ai_chatgpt_models(registration_id,slug,display_name,position) VALUES($1,$2,$3,$4)',[registrationId,model.slug,model.displayName,model.position]);});return{models,observedAt:new Date().toISOString()};}
  async markTerminalFailure(householdId:string,registrationId:string,code:'AI_PLAN_USAGE_LIMITED'|'AI_PLAN_NOT_ELIGIBLE'|'AI_PLAN_PERMISSION_REQUIRED'|'AI_REAUTHORIZATION_REQUIRED',_providerReason?:string){const status=code==='AI_PLAN_USAGE_LIMITED'?'usage_limited':code==='AI_PLAN_NOT_ELIGIBLE'?'not_eligible':'reauthorization_required';await transaction(async(client)=>{await client.query('SELECT household_id FROM ai_settings WHERE household_id=$1 FOR UPDATE',[householdId]);await client.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[registrationId]);const updated=await client.query(`UPDATE ai_chatgpt_registrations SET status=$3,last_error_code=$4,revision=revision+1,updated_at=clock_timestamp() WHERE id=$1 AND household_id=$2 AND status='connected' RETURNING id`,[registrationId,householdId,status,code]);if(updated.rowCount)await client.query(`UPDATE ai_settings SET availability_status='error',availability_error_code=$3,availability_checked_at=clock_timestamp(),availability_checked_revision=revision,updated_at=clock_timestamp() WHERE household_id=$1 AND provider='chatgpt_subscription' AND active_chatgpt_registration_id=$2`,[householdId,registrationId,code]);});}
  async markUsageLimited(householdId:string,registrationId:string){await this.markTerminalFailure(householdId,registrationId,'AI_PLAN_USAGE_LIMITED','subscription_sharing_usage_limit_exceeded');}
  async resume(actor:Actor,registrationId:string,expectedRevision:number){const row=await transaction(async(client)=>{const current=(await client.query<RegistrationRow>(`SELECT r.* FROM ai_chatgpt_registrations r JOIN memberships m ON m.id=r.owner_membership_id AND m.account_id=r.owner_account_id AND m.household_id=r.household_id AND m.capabilities ? 'household.manage' JOIN accounts a ON a.id=r.owner_account_id AND a.disabled_at IS NULL WHERE r.id=$1 AND r.household_id=$2 FOR UPDATE OF r`,[registrationId,actor.householdId])).rows[0];if(!current||current.owner_account_id!==actor.accountId||current.owner_membership_id!==actor.membershipId)throw new DomainError('FORBIDDEN',403);if(current.revision!==expectedRevision||!['usage_limited','not_eligible'].includes(current.status)||!current.credential_ciphertext)throw new DomainError('REVISION_CONFLICT',409);const updated=(await client.query<RegistrationRow>(`UPDATE ai_chatgpt_registrations SET status='connected',last_error_code=NULL,revision=revision+1,updated_at=clock_timestamp() WHERE id=$1 RETURNING *`,[registrationId])).rows[0]!;await client.query(`INSERT INTO audit_events(installation_id,household_id,actor_type,actor_id,action,subject_type,subject_id,metadata) VALUES($1,$2,'account',$3,'ai.chatgpt_usage_resumed','ai_chatgpt_registration',$4,$5)`,[actor.installationId,actor.householdId,actor.accountId,registrationId,JSON.stringify({previousStatus:current.status,previousRevision:expectedRevision,newRevision:updated.revision})]);return updated;});return safeRegistration(row,actor);}
  async select(actor:Actor,registrationId:string,expectedRevision:number){return transaction(async(client)=>{const settings=(await client.query<{revision:number}>('SELECT revision FROM ai_settings WHERE household_id=$1 FOR UPDATE',[actor.householdId])).rows[0];if(!settings||settings.revision!==expectedRevision)throw new DomainError('REVISION_CONFLICT',409);const row=(await client.query<RegistrationRow>(`SELECT r.* FROM ai_chatgpt_registrations r JOIN memberships m ON m.id=r.owner_membership_id AND m.account_id=r.owner_account_id AND m.household_id=r.household_id AND m.capabilities ? 'household.manage' JOIN accounts a ON a.id=r.owner_account_id AND a.disabled_at IS NULL WHERE r.id=$1 AND r.household_id=$2 FOR UPDATE OF r`,[registrationId,actor.householdId])).rows[0];if(!row)throw new DomainError('NOT_FOUND',404);if(row.owner_account_id!==actor.accountId||row.owner_membership_id!==actor.membershipId)throw new DomainError('FORBIDDEN',403);if(row.status!=='connected'||!row.credential_ciphertext)throw new DomainError('AI_REAUTHORIZATION_REQUIRED',422);const updated=(await client.query<{revision:number;active_chatgpt_registration_id:string|null}>(`UPDATE ai_settings SET active_chatgpt_registration_id=$2,default_model=CASE WHEN provider<>'chatgpt_subscription' THEN default_model WHEN EXISTS(SELECT 1 FROM ai_chatgpt_models WHERE registration_id=$2 AND slug=default_model) THEN default_model ELSE '' END,strong_model=CASE WHEN provider<>'chatgpt_subscription' THEN strong_model WHEN EXISTS(SELECT 1 FROM ai_chatgpt_models WHERE registration_id=$2 AND slug=strong_model) THEN strong_model ELSE '' END,revision=revision+1,availability_status='not_tested',availability_error_code=NULL,availability_checked_at=NULL,availability_checked_revision=NULL,updated_at=clock_timestamp() WHERE household_id=$1 AND revision=$3 RETURNING revision,active_chatgpt_registration_id`,[actor.householdId,registrationId,expectedRevision])).rows[0]!;return{activeRegistrationId:updated.active_chatgpt_registration_id,revision:updated.revision,registration:safeRegistration(row,actor)};});}
  async disconnect(actor:Actor,registrationId:string,expectedRevision:number){const fenced=await transaction(async(client)=>{await client.query('SELECT household_id FROM ai_settings WHERE household_id=$1 FOR UPDATE',[actor.householdId]);await client.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[registrationId]);const row=(await client.query<RegistrationRow>('SELECT * FROM ai_chatgpt_registrations WHERE id=$1 AND household_id=$2 FOR UPDATE',[registrationId,actor.householdId])).rows[0];if(!row)throw new DomainError('NOT_FOUND',404);if(row.owner_account_id!==actor.accountId)throw new DomainError('FORBIDDEN',403);if(row.revision!==expectedRevision)throw new DomainError('REVISION_CONFLICT',409);let bundle:CredentialBundle|undefined;if(row.credential_ciphertext)try{bundle=JSON.parse(await this.vault.decrypt(`${actor.householdId}:${row.id}`,row.credential_ciphertext)) as CredentialBundle;}catch{}const updated=(await client.query<RegistrationRow>(`UPDATE ai_chatgpt_registrations SET credential_ciphertext=NULL,access_expires_at=NULL,status='revocation_unconfirmed',generation=generation+1,revision=revision+1,last_error_code='revocation_unconfirmed',updated_at=clock_timestamp() WHERE id=$1 AND household_id=$2 RETURNING *`,[row.id,actor.householdId])).rows[0]!;await client.query(`UPDATE ai_settings SET enabled=CASE WHEN provider=$2 THEN false ELSE enabled END,active_chatgpt_registration_id=NULL,revision=revision+1,updated_at=clock_timestamp() WHERE household_id=$1 AND active_chatgpt_registration_id=$3`,[actor.householdId,'chatgpt_subscription' satisfies AiProviderId,row.id]);return{row,updated,bundle};});let confirmed=false;if(fenced.bundle){try{const discovery=await this.transport(`${ISSUER}/.well-known/openid-configuration`,{headers:{accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(10_000)});const doc=await boundedJson(discovery);if(object(doc)&&typeof doc.revocation_endpoint==='string'&&doc.revocation_endpoint.startsWith(`${ISSUER}/`)){const response=await this.transport(doc.revocation_endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({token:fenced.bundle.refreshToken,token_type_hint:'refresh_token',client_id:fenced.row.issued_client_id}),redirect:'error',signal:AbortSignal.timeout(10_000)});confirmed=response.status===200;}}catch{confirmed=false;}}if(confirmed)await pool.query(`UPDATE ai_chatgpt_registrations SET status='disconnected',last_error_code=NULL,updated_at=clock_timestamp() WHERE id=$1 AND household_id=$2 AND credential_ciphertext IS NULL`,[registrationId,actor.householdId]);return{registration:{...safeRegistration(fenced.updated,actor),status:confirmed?'disconnected':'revocation_unconfirmed'},revocationConfirmed:confirmed};}
}
