// Targeted M2.3 admin smoke. It creates and removes one synthetic draft and never calls an AI provider.
import { chromium, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

const baseURL=process.env.BASE_URL??"http://samvev-m1-app-1:4173";
const publicOrigin=process.env.PUBLIC_ORIGIN??new URL(baseURL).origin;
const browser=await chromium.launch({headless:true});
const ownerContext=await browser.newContext({baseURL,viewport:{width:390,height:844},reducedMotion:"reduce",extraHTTPHeaders:{Origin:publicOrigin}});
const limitedContext=await browser.newContext({baseURL,extraHTTPHeaders:{Origin:publicOrigin}});
const login=async(context,email)=>{const response=await context.request.post('/api/v1/auth/login',{data:{email,password:'Synthetic-pilot-pass-42'}});expect(response.ok(),await response.text()).toBeTruthy();return (await context.request.get('/api/v1/me')).json();};
const owner=await login(ownerContext,'owner@pilot.invalid');await login(limitedContext,'limited@pilot.invalid');
const headers={'X-CSRF-Token':owner.csrfToken};await ownerContext.request.patch('/api/v1/me/preferences',{headers,data:{locale:'en',theme:'light'}});
const page=await ownerContext.newPage();const limited=await limitedContext.newPage();for(const current of [page,limited]){current.on('pageerror',(error)=>console.error('PAGE ERROR',error));current.on('console',(message)=>{if(message.type()==='error')console.error('BROWSER ERROR',message.text());});}let createdId;
try{
  await page.route('**/api/v1/**',route=>route.continue({headers:{...route.request().headers(),origin:publicOrigin}}));
  await page.goto('/');await expect(page.getByRole('button',{name:'Tasks',exact:true})).toBeVisible();const navBoxes=await page.locator('.sidebar nav .nav-item').evaluateAll((items)=>items.map((item)=>{const box=item.getBoundingClientRect();return {top:box.top,bottom:box.bottom};}));expect(navBoxes).toHaveLength(5);expect(new Set(navBoxes.map((box)=>Math.round(box.top))).size).toBe(1);expect(Math.max(...navBoxes.map((box)=>box.bottom))).toBeLessThanOrEqual(844);await page.getByRole('button',{name:'Tasks',exact:true}).click();await expect(page.getByRole('heading',{name:'Tasks'})).toBeVisible();
  await page.getByRole('button',{name:'New task'}).click();await expect(page.getByLabel('Plain-language instruction')).toBeVisible();await expect(page.getByLabel('AI policy')).toContainText('Default AI');await page.getByRole('button',{name:'Cancel'}).click();
  const householdId=owner.memberships[0].household_id;const displays=await (await ownerContext.request.get(`/api/v1/households/${householdId}/displays`)).json();const people=await (await ownerContext.request.get(`/api/v1/households/${householdId}/people`)).json();
  const created=await ownerContext.request.post(`/api/v1/households/${householdId}/monitors`,{headers,data:{name:'Synthetic M2.3 smoke task',instruction:'Find future synthetic trip days and notify the selected recipient the evening before.',sourceUrl:'https://example.com/synthetic-plan',checkIntervalMinutes:1440,noticeDaysBefore:1,noticeLocalTime:'18:00',providerPolicy:'default',modelTier:'routine',targets:{personIds:people.people[0]?[people.people[0].id]:[],displayIds:displays.displays[0]?[displays.displays[0].id]:[]}}});expect(created.ok(),await created.text()).toBeTruthy();let uiTask=await created.json();createdId=uiTask.id;
  await page.unroute('**/api/v1/**');await page.route('**/api/v1/**',async route=>{const request=route.request();const url=new URL(request.url());if(url.pathname.endsWith('/monitors')&&request.method()==='GET')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({tasks:[uiTask]})});if(url.pathname.includes(`/monitors/${createdId}/`)&&request.method()==='POST'){const action=url.pathname.split('/').at(-1);uiTask={...uiTask,revision:uiTask.revision+1};if(action==='interpret')uiTask={...uiTask,checkIntervalMinutes:60,noticeDaysBefore:1,noticeLocalTime:'18:00',interpretedRule:{summary:'Find future trip days and notify the selected display the evening before.',eventTypes:['trip'],keywords:['trip'],people:['A'],noticeDaysBefore:1,noticeLocalTime:'18:00',checkIntervalMinutes:60}};if(action==='approve')uiTask={...uiTask,state:'active',approvedRevision:uiTask.revision,nextCheckAt:'2030-09-18T18:00:00.000Z',lastCheckedAt:'2030-09-17T18:00:00.000Z',lastChangedAt:'2030-09-17T18:00:00.000Z',lastResult:'1 event(s)',stats:{checks:14,aiCalls:1,unchanged:13}};if(action==='pause')uiTask={...uiTask,state:'paused',nextCheckAt:null};if(action==='resume')uiTask={...uiTask,state:'active',approvedRevision:uiTask.revision,nextCheckAt:'2030-09-18T18:00:00.000Z'};return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(uiTask)});}return route.continue({headers:{...request.headers(),origin:publicOrigin}});});
  await page.reload();await page.getByRole('button',{name:'Tasks',exact:true}).click();const card=page.getByRole('article').filter({hasText:'Synthetic M2.3 smoke task'});await expect(card).toContainText('Needs approval');await card.getByRole('button',{name:'Interpret'}).click();const preview=card.getByRole('status');await expect(preview).toBeFocused();await expect(preview).toContainText('Interval: 60 minutes');await expect(preview).toContainText('Days before: 1 · Time: 18:00 · Europe/Oslo');await expect(preview).toContainText(displays.displays[0]?.name??people.people[0].display_name);await card.getByRole('button',{name:'Approve and activate'}).click();await expect(card).toContainText('Active');await expect(card).toContainText('Source checks: 14 · AI calls: 1');await expect(card).toContainText('Events found: 1');await expect(card).toContainText('Last check');await expect(card).toContainText('Last change');await card.getByRole('button',{name:'Pause'}).click();await expect(card).toContainText('Paused');await card.getByRole('button',{name:'Resume'}).click();await expect(card).toContainText('Active');
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations.map((v)=>v.id)).toEqual([]);
  await limited.goto('/');await expect(limited.getByRole('button',{name:'Tasks',exact:true})).toHaveCount(0);
  console.log('PASS admin reviews, approves, pauses and resumes a task; status/counters render, axe passes, and non-admin navigation hides task controls');
}finally{
  if(createdId){const listing=await (await ownerContext.request.get(`/api/v1/households/${owner.memberships[0].household_id}/monitors`)).json();const task=listing.tasks.find((item)=>item.id===createdId);if(task)await ownerContext.request.delete(`/api/v1/households/${owner.memberships[0].household_id}/monitors/${createdId}`,{headers,data:{expectedRevision:task.revision}});}
  await browser.close();
}
