import { registrationState, registrationIdentity, purposeKey, attemptState, forecastPresentation, type UsageForecast } from "./ai-presentation";
import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from './api';
import { formatDate } from './time';
import { Check, ErrorNotice, Field, Icon, Loading, useI18n } from './ui';
import { en, type TranslationKey } from './locales/en';

type ProviderId='openai'|'chatgpt_subscription'|'openai_compatible'|'gemini';
type ReasoningEffort='none'|'low'|'medium'|'high';
type Configuration={provider:ProviderId;hasApiKey:boolean;baseUrl:string|null;defaultModel:string;strongModel:string;defaultReasoningEffort:ReasoningEffort;strongReasoningEffort:ReasoningEffort};
type Registration={id:string;label:string;status:string;revision:number;isOwner:boolean;canManage:boolean;email?:string|null;subjectSuffix?:string;errorCode?:string|null};
type AiSettings=Configuration&{enabled:boolean;revision:number;savedProviders:Configuration[];availability:{status:'not_tested'|'not_configured'|'available'|'unavailable'|'error';available:boolean;errorCode:string|null;checkedAt:string|null};chatgpt:{hostId:string;activeRegistrationId:string|null;registrations:Registration[];usageUrl:string}};
type Counts={calls:number;inputTokens:number;outputTokens:number};
type Pricing={amount?:string|null;estimatedCredits?:string|null;knownCalls:number;unknownPricedAttempts:number;sourceUrl:string;observedAt:string|null;effectiveFrom:string|null};
type AiUsage={period:{days:number;from:string|null;to:string|null};summary:{requests:number;successes:number;failures:number;inputTokens:number;outputTokens:number;unknownUsageCount:number;preflightRejections:number;pendingAttempts:number;legacyUnknownAttempts:number};byDay:(Counts&{date:string;unknownUsageCount:number})[];byModel:(Counts&{model:string;route:string})[];byPurpose:(Counts&{purpose:string;category:string})[];chatGptCredits:Pricing;apiEquivalent:Pricing;forecast:{chatGptCredits:UsageForecast;apiUsd:UsageForecast};recent:{provider:ProviderId;route:string|null;model:string|null;actualModel:string|null;requestedModel:string|null;actualServiceTier:string|null;purpose:string;category:string|null;success:boolean;outcome?:string;actualDispatch?:boolean|null;errorCode:string|null;inputTokens:number|null;outputTokens:number|null;occurredAt:string}[]};
type Draft=Omit<Configuration,'hasApiKey'|'baseUrl'>&{enabled:boolean;baseUrl:string};
const asDraft=(settings:AiSettings):Draft=>({enabled:settings.enabled,provider:settings.provider,baseUrl:settings.baseUrl??'',defaultModel:settings.defaultModel,strongModel:settings.strongModel,defaultReasoningEffort:settings.defaultReasoningEffort??'none',strongReasoningEffort:settings.strongReasoningEffort??'medium'});
const routeKey=(route:string):TranslationKey=>route==='openai'||route==='openai_api'?'aiRouteApi':route==='chatgpt_subscription'||route==='chatgpt_plan'?'aiRoutePlan':route==='openai_compatible'||route==='local'?'aiRouteLocal':'hubUnknown';
const safeError=(code:string|null|undefined):TranslationKey=>code&&code in en?code as TranslationKey:'INTERNAL_ERROR';
export function AiSettingsPanel({householdId,ownerAccountId,timezone}:{householdId:string;ownerAccountId:string;timezone:string}){
 const {t,locale}=useI18n();const base=`/households/${householdId}/ai`;
 const [settings,setSettings]=useState<AiSettings>();const [draft,setDraft]=useState<Draft>();const [usage,setUsage]=useState<AiUsage>();const [days,setDays]=useState<7|30>(30);
 const [apiKey,setApiKey]=useState('');const [removeKey,setRemoveKey]=useState(false);const [error,setError]=useState<unknown>();const [loadError,setLoadError]=useState<unknown>();const [busy,setBusy]=useState(false);const [saved,setSaved]=useState(false);const [testResult,setTestResult]=useState<{available:boolean;errorCode?:string}>();const [models,setModels]=useState<{slug:string;displayName:string}[]>([]);
 const load=useCallback(async()=>{setLoadError(undefined);try{const [s,u]=await Promise.all([api<AiSettings>(`${base}/settings`),api<AiUsage>(`${base}/usage?days=${days}`)]);setSettings(s);setDraft(asDraft(s));setUsage(u);setApiKey('');setRemoveKey(false)}catch(e){setLoadError(e)}},[base,days]);
 useEffect(()=>{void load()},[load]);
 const dirty=useMemo(()=>Boolean(settings&&draft&&(JSON.stringify(draft)!==JSON.stringify(asDraft(settings))||apiKey||removeKey)),[settings,draft,apiKey,removeKey]);
 const activeRegistration=settings?.chatgpt.registrations.find(r=>r.id===settings.chatgpt.activeRegistrationId);
 const ownsPlan=Boolean(activeRegistration?.isOwner&&activeRegistration.canManage);
 const selectedSaved=settings?.savedProviders.find(p=>p.provider===draft?.provider);
 const endpointChanged=draft?.provider==='openai_compatible'&&draft.baseUrl!==(selectedSaved?.baseUrl??settings?.baseUrl??'');
 const hasKey=!endpointChanged&&(selectedSaved?.hasApiKey??(draft?.provider===settings?.provider&&Boolean(settings?.hasApiKey)));
 const invalidKey=draft?.provider==='openai'&&apiKey.length>0&&apiKey.length<20;
 const planSelected=draft?.provider==='chatgpt_subscription';
 const update=(next:Partial<Draft>)=>{if(draft)setDraft({...draft,...next});setSaved(false)};
 const chooseProvider=(provider:ProviderId)=>{if(!draft||!settings)return;const savedProvider=settings.savedProviders.find(p=>p.provider===provider);setDraft({...draft,provider,baseUrl:savedProvider?.baseUrl??'',defaultModel:savedProvider?.defaultModel??'',strongModel:savedProvider?.strongModel??'',defaultReasoningEffort:savedProvider?.defaultReasoningEffort??'none',strongReasoningEffort:savedProvider?.strongReasoningEffort??'medium'});setApiKey('');setRemoveKey(false);setSaved(false);setTestResult(undefined)};
 const action=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError(undefined);setSaved(false);try{await fn()}catch(e){setError(e)}finally{setBusy(false)}};
 const save=()=>action(async()=>{if(!settings||!draft)return;const body:Record<string,unknown>={enabled:draft.enabled,provider:draft.provider,defaultModel:draft.defaultModel,strongModel:draft.strongModel,expectedRevision:settings.revision};if(draft.provider==='openai_compatible')Object.assign(body,{baseUrl:draft.baseUrl,defaultReasoningEffort:draft.defaultReasoningEffort,strongReasoningEffort:draft.strongReasoningEffort});if(!planSelected){if(apiKey)body.apiKey=apiKey;else if(removeKey)body.apiKey=null}await api(`${base}/settings`,'PATCH',body);await load();setSaved(true)});
 const test=(modelTier:'routine'|'strong')=>action(async()=>{setTestResult(await api(`${base}/test`,'POST',{modelTier},{timeoutMs:35000}));await load()});
 const registrationAction=(registration:Registration,operation:'disconnect'|'resume'|'select')=>action(async()=>{if(operation==='disconnect'&&!window.confirm(t('aiDisconnectConfirm')))return;await api(`${base}/chatgpt/${registration.id}/${operation}`,'POST',{expectedRevision:operation==='select'?settings!.revision:registration.revision});setModels([]);await load()});
 const loadModels=()=>action(async()=>{if(!activeRegistration?.isOwner)return;const result=await api<{models:{slug:string;displayName:string}[]}>(`${base}/chatgpt/${activeRegistration.id}/models`);setModels(result.models)});
 if(!settings||!draft||!usage)return <section className="ai-settings" aria-label={t('aiTitle')}><ErrorNotice error={loadError}/>{!loadError?<Loading/>:<button className="button" onClick={()=>void load()}>{t('retry')}</button>}</section>;
 const format=(value:number)=>new Intl.NumberFormat(locale).format(value);
 const modelField=(field:'defaultModel'|'strongModel')=><Field label={t(field==='defaultModel'?'aiRoutineModel':'aiStrongModel')} hint={t(field==='defaultModel'?'aiRoutineModelHint':'aiStrongModelHint')}>{planSelected?<select value={draft[field]} disabled={busy||!ownsPlan||models.length===0} onChange={e=>update({[field]:e.target.value})}><option value="">{t('aiChooseModel')}</option>{draft[field]&&!models.some(m=>m.slug===draft[field])&&<option value={draft[field]}>{draft[field]}</option>}{models.map(m=><option key={m.slug} value={m.slug}>{m.displayName}</option>)}</select>:<input value={draft[field]} maxLength={100} autoComplete="off" disabled={busy} onChange={e=>update({[field]:e.target.value})}/>}</Field>;
 const source=(pricing:Pricing)=><p className="field-hint ai-price-source"><a href={pricing.sourceUrl} target="_blank" rel="noreferrer">{t('aiPriceSource')}</a>{pricing.observedAt?<> · {t('aiPriceChecked',{date:formatDate(pricing.observedAt,locale,timezone,{day:'numeric',month:'short',year:'numeric'})})}</>:<> · {t('aiPriceNoObservation')}</>}{pricing.effectiveFrom&&<> · {t('aiPriceEffective',{date:pricing.effectiveFrom})}</>}</p>;
 return <section className="ai-settings" aria-labelledby="ai-title">
  <header className="section-heading ai-heading"><div><p className="eyebrow">{t('aiEyebrow')}</p><h1 id="ai-title">{t('aiTitle')}</h1><p>{t('aiBody')}</p></div><span className={`ai-availability ai-${settings.availability.status}`} data-testid="ai-availability">{t(({not_tested:'aiStatusNotTested',not_configured:'aiStatusNotConfigured',available:'aiStatusAvailable',unavailable:'aiStatusUnavailable',error:'aiStatusError'} as const)[settings.availability.status])}</span></header>
  <ErrorNotice error={loadError}/><ErrorNotice error={error}/>
  <section className="ai-route-banner"><Icon name="shield"/><div><strong>{t('aiActiveRoute')}: {t(routeKey(settings.provider))}</strong><p>{!settings.enabled?t('aiDisabledRoute'):t(settings.provider==='chatgpt_subscription'?'aiPlanBilling':settings.provider==='openai'?'aiApiBilling':'aiLocalBilling')}</p>{settings.provider==='chatgpt_subscription'&&<p>{activeRegistration?.isOwner?registrationIdentity(activeRegistration):t('aiOtherOwner')}</p>}</div></section>
  <div className="ai-layout"><div className="ai-primary"><form className="ai-card form-stack" aria-busy={busy} onSubmit={e=>{e.preventDefault();void save()}}>
   <div className="ai-card-heading"><div><h2>{t('aiConfiguration')}</h2><p>{t('aiNoFallback')}</p></div><Check label={t('aiEnabled')} checked={draft.enabled} disabled={busy||(planSelected&&!ownsPlan)} onChange={enabled=>update({enabled})}/></div>
   <fieldset className="ai-providers"><legend>{t('aiProvider')}</legend>{(['chatgpt_subscription','openai','openai_compatible'] as const).map(provider=><label className={`ai-provider ${draft.provider===provider?'active':''}`} key={provider}><input type="radio" name="ai-provider" value={provider} checked={draft.provider===provider} disabled={busy} onChange={()=>chooseProvider(provider)}/><span><strong>{t(routeKey(provider))}</strong><small>{t(provider==='chatgpt_subscription'?'aiProviderChatGptHint':provider==='openai'?'aiProviderOpenAiHint':'aiProviderLocalHint')}</small></span></label>)}</fieldset>
   {planSelected&&<div className="ai-plan-configuration"><p>{t('aiPlanFirstUse')}</p><p className="field-hint">{ownsPlan?t('aiPlanOwnerOnly'):t('aiConnectBeforeEnable')}</p>{ownsPlan&&<button className="button" type="button" disabled={busy||activeRegistration?.status!=='connected'} onClick={()=>void loadModels()}><Icon name="spark"/>{t('aiLoadModels')}</button>}{models.length>0&&<p role="status" className="field-hint">{t('aiModelsLoaded',{count:models.length})}</p>}</div>}
   {draft.provider==='openai_compatible'&&<Field label={t('aiBaseUrl')} hint={t('aiBaseUrlHint')}><input type="url" value={draft.baseUrl} maxLength={2048} required disabled={busy} autoComplete="off" onChange={e=>update({baseUrl:e.target.value})}/></Field>}
   <div className="form-grid">{modelField('defaultModel')}{modelField('strongModel')}</div>
   {draft.provider==='openai_compatible'&&<div className="form-grid">{(['defaultReasoningEffort','strongReasoningEffort'] as const).map(field=><Field key={field} label={t(field==='defaultReasoningEffort'?'aiRoutineReasoning':'aiStrongReasoning')} hint={t(field==='defaultReasoningEffort'?'aiRoutineReasoningHint':'aiStrongReasoningHint')}><select value={draft[field]} disabled={busy} onChange={e=>update({[field]:e.target.value as ReasoningEffort})}>{(['none','low','medium','high'] as const).map(value=><option key={value} value={value}>{t(({none:'aiReasoningNone',low:'aiReasoningLow',medium:'aiReasoningMedium',high:'aiReasoningHigh'} as const)[value])}</option>)}</select></Field>)}</div>}
   {!planSelected&&<><Field label={t(draft.provider==='openai_compatible'?'aiApiKeyOptional':'aiApiKey')} hint={t(draft.provider==='openai_compatible'?'aiApiKeyOptionalHint':'aiApiKeyHint')}><input type="password" value={apiKey} minLength={draft.provider==='openai'?20:1} maxLength={512} autoComplete="new-password" disabled={busy||removeKey} placeholder={hasKey?t('aiApiKeyConfigured'):t(draft.provider==='openai'?'aiApiKeyEmpty':'aiApiKeyOptionalEmpty')} onChange={e=>{setApiKey(e.target.value);setSaved(false)}}/></Field>{hasKey&&<Check label={t('aiRemoveApiKey')} checked={removeKey} disabled={busy} onChange={checked=>{setRemoveKey(checked);setApiKey('')}}/>}{invalidKey&&<p className="field-error">{t('aiApiKeyLength')}</p>}<p className="field-hint">{t('aiSavedRoutes')}</p></>}
   <div className="form-actions"><span role="status">{saved?t('aiSettingsSaved'):''}</span><button type="submit" className="button primary" disabled={!dirty||busy||invalidKey||(planSelected&&!ownsPlan)}>{busy?t('saving'):t('save')}<Icon name="arrow"/></button></div>
  </form>
  <section className="ai-card ai-onboarding" aria-labelledby="ai-chatgpt-title"><h2 id="ai-chatgpt-title">{t('aiConnectChatGpt')}</h2><p>{t('aiConnectionSeparate')}</p>
   {settings.chatgpt.registrations.length>0&&<div className="ai-registrations">{settings.chatgpt.registrations.map(r=><article key={r.id}><strong>{r.isOwner?registrationIdentity(r):t('aiOtherOwner')}</strong><p>{t(registrationState(r.status))}</p>{r.id===settings.chatgpt.activeRegistrationId&&<span className="ai-selected-account">{t('aiSelectedAccount')}</span>}{r.canManage&&r.status==='connected'&&r.id!==settings.chatgpt.activeRegistrationId&&<button type="button" className="button" disabled={busy||dirty} onClick={()=>void registrationAction(r,'select')}>{t('aiSelectAccount')}</button>}{r.errorCode&&r.isOwner&&r.errorCode in en&&<p className="field-hint">{t(safeError(r.errorCode))}</p>}{r.canManage&&!['disconnected','revocation_unconfirmed'].includes(r.status)&&<div className="ai-test-actions">{['usage_limited','not_eligible'].includes(r.status)&&<button type="button" className="button" disabled={busy} onClick={()=>void registrationAction(r,'resume')}>{t('aiResumePlan')}</button>}<button type="button" className="button subtle" disabled={busy} onClick={()=>void registrationAction(r,'disconnect')}>{t('aiDisconnect')}</button></div>}</article>)}</div>}
   <details className="ai-connect-steps" open={!settings.chatgpt.registrations.some(r=>r.isOwner&&r.status==='connected')}><summary>{t('aiConnectSteps')}</summary><ol>
    <li><strong>{t('aiConnectStep1')}</strong><p>{t('aiConnectDownload')}</p><div className="ai-source-links"><a href="https://github.com/pabben/samvev/blob/feat/m3-family-hub/scripts/chatgpt-connect.ts" target="_blank" rel="noreferrer">chatgpt-connect.ts</a><a href="https://github.com/pabben/samvev/blob/feat/m3-family-hub/scripts/chatgpt-connect-core.mjs" target="_blank" rel="noreferrer">chatgpt-connect-core.mjs</a></div><pre><code>{`node ./chatgpt-connect.ts --host-id '${settings.chatgpt.hostId}' --output "$HOME/samvev-chatgpt-credential.json"`}</code></pre><p className="field-hint">{t('aiConsentScope')}</p></li>
    <li><strong>{t('aiConnectStep2')}</strong><p>{t('aiSecureCopy')}</p><pre><code>{'scp "$HOME/samvev-chatgpt-credential.json" <ssh-user>@<samvev-host>:<private-credential-path>'}</code></pre><p className="field-hint">{t('aiNoTokenPaste')}</p></li>
    <li><strong>{t('aiConnectStep3')}</strong><p>{t('aiImportOnServer')}</p><pre><code>{`cd <samvev-project-directory>\nnpm run ai:chatgpt-import -- --household '${householdId}' --owner-account '${ownerAccountId}' --file <private-credential-path>`}</code></pre><p className="field-hint">{t('aiSecureDelete')}</p><pre><code>{'rm -- <private-credential-path>'}</code></pre><button type="button" className="button" disabled={busy} onClick={()=>void action(load)}>{t('aiRefreshConnection')}</button></li>
   </ol><a href="https://github.com/pabben/samvev/blob/feat/m3-family-hub/docs/CHATGPT_PLAN_CONNECTION.md" target="_blank" rel="noreferrer">{t('aiConnectionGuide')}</a><p className="field-hint">{t('aiStableHost')}: <code>{settings.chatgpt.hostId}</code></p></details>
   <a className="ai-usage-link" href="https://chatgpt.com/settings/usage" target="_blank" rel="noreferrer">{t('aiAccountUsage')}<Icon name="arrow"/></a>
  </section>
  <section className="ai-card" aria-labelledby="ai-test-title"><h2 id="ai-test-title">{t('aiConnectionTest')}</h2><p>{t(settings.provider==='openai_compatible'?'aiLocalConnectionTestHint':'aiConnectionTestHint')}</p><div className="notice offline"><Icon name="spark"/><span>{t(settings.provider==='chatgpt_subscription'?'aiPlanTestWarning':settings.provider==='openai_compatible'?'aiLocalTestUsageWarning':'aiTestUsageWarning')}</span></div>{settings.availability.errorCode&&<p>{t(safeError(settings.availability.errorCode))}</p>}{dirty&&<p className="field-hint">{t('aiSaveBeforeTest')}</p>}<div className="ai-test-actions">{(['routine','strong'] as const).map(tier=><button key={tier} className="button" disabled={dirty||busy||(settings.provider==='chatgpt_subscription'&&(!ownsPlan||activeRegistration?.status!=='connected'))} onClick={()=>void test(tier)}>{t(tier==='routine'?'aiTestRoutine':'aiTestStrong')}</button>)}</div>{testResult&&<div className={`notice ${testResult.available?'':'error'}`} role="status" data-testid="ai-test-result">{testResult.available?t('aiStatusAvailable'):t(safeError(testResult.errorCode))}</div>}<p className="field-hint">{t('aiAvailabilityScope')}</p></section>
  </div><aside className="ai-secondary">
   <section className="ai-card" aria-labelledby="ai-usage-title"><div className="ai-card-heading"><h2 id="ai-usage-title">{t('aiUsage')}</h2><Field label={t('aiPeriod')}><select value={days} disabled={busy||dirty} onChange={e=>setDays(Number(e.target.value) as 7|30)}><option value={7}>{t('aiDays',{count:7})}</option><option value={30}>{t('aiDays',{count:30})}</option></select></Field></div><p className="field-hint">{t('aiUsageOwnerScope')}</p><p className="field-hint">{usage.period.from} – {usage.period.to} · UTC</p><dl className="ai-summary"><div><dt>{t('aiRequests')}</dt><dd>{format(usage.summary.requests)}</dd></div><div><dt>{t('aiSucceeded')}</dt><dd>{format(usage.summary.successes)}</dd></div><div><dt>{t('aiKnownTokens')}</dt><dd>{format(usage.summary.inputTokens+usage.summary.outputTokens)}</dd></div><div><dt>{t('aiUnknownUsage')}</dt><dd>{format(usage.summary.unknownUsageCount)}</dd></div></dl><p className="field-hint">{t('aiUsageStateCounts',{preflight:usage.summary.preflightRejections,pending:usage.summary.pendingAttempts,legacy:usage.summary.legacyUnknownAttempts})}</p>
    <details className="ai-breakdown"><summary>{t('aiByDay')}</summary><div className="ai-table-wrap"><table><thead><tr><th>{t('aiDay')}</th><th>{t('aiRequests')}</th><th>{t('aiKnownTokens')}</th></tr></thead><tbody>{usage.byDay.map(d=><tr key={d.date}><th>{d.date}</th><td>{d.calls}</td><td>{format(d.inputTokens+d.outputTokens)}{d.unknownUsageCount>0&&` + ${t('hubUnknown')}`}</td></tr>)}</tbody></table></div></details>
    <details className="ai-breakdown"><summary>{t('aiByModel')}</summary>{usage.byModel.length?usage.byModel.map((m,i)=><div className="ai-usage-row" key={i}><strong>{m.model==='unreported'?t('aiModelUnreported'):m.model}</strong><span>{t(routeKey(m.route))} · {t('aiCallCount',{count:m.calls})}</span><small>{t('aiKnownTokens')}: {format(m.inputTokens+m.outputTokens)}</small></div>):<p>{t('aiNoUsage')}</p>}</details>
    <details className="ai-breakdown"><summary>{t('aiByPurpose')}</summary>{usage.byPurpose.length?usage.byPurpose.map((p,i)=><div className="ai-usage-row" key={i}><strong>{purposeLabel(p.purpose,t)}</strong><span>{t(p.category==='normal'?'aiNormalUse':'aiSetupTests')} · {t('aiCallCount',{count:p.calls})}</span><small>{t('aiKnownTokens')}: {format(p.inputTokens+p.outputTokens)}</small></div>):<p>{t('aiNoUsage')}</p>}</details>
   </section>
   <section className="ai-card ai-costs"><p className="eyebrow">{t('aiEstimate')}</p><h2>{t('aiPlanCredits')}</h2><p className="ai-cost-value">{usage.chatGptCredits.estimatedCredits??t('hubUnknown')}</p><p>{t('aiCreditsEstimateHint')}</p><p className="field-hint">{t('aiPricingCoverage',{known:usage.chatGptCredits.knownCalls,unknown:usage.chatGptCredits.unknownPricedAttempts})}</p>{source(usage.chatGptCredits)}<p className="notice">{t('aiBalanceUnknown')}</p><a className="ai-usage-link" href="https://chatgpt.com/settings/usage" target="_blank" rel="noreferrer">{t('aiAccountUsage')}<Icon name="arrow"/></a></section>
   <section className="ai-card ai-costs"><p className="eyebrow">{t('aiScenario')}</p><h2>{t('aiApiEquivalent')}</h2><p className="ai-cost-value">{usage.apiEquivalent.amount===null?t('hubUnknown'):`${usage.apiEquivalent.amount} USD`}</p><p>{t('aiApiScenarioHint')}</p><p className="field-hint">{t('aiApiComparisonAssumption')}</p><p className="field-hint">{t('aiPricingCoverage',{known:usage.apiEquivalent.knownCalls,unknown:usage.apiEquivalent.unknownPricedAttempts})}</p>{source(usage.apiEquivalent)}</section>
   <section className="ai-card"><h2>{t('aiForecast')}</h2>{(['chatGptCredits','apiUsd'] as const).map(key=>{const forecast=usage.forecast[key];const presentation=forecastPresentation(forecast);return <section className="ai-forecast-route" key={key}><h3>{t(key==='chatGptCredits'?'aiMonthlyCredits':'aiMonthlyApi')}</h3>{presentation.amount!==null?<p className="ai-cost-value">{presentation.amount}{key==='apiUsd'?' USD':` ${t('aiCreditUnit')}`}</p>:<p>{t(presentation.reasonKey)}</p>}<p className="field-hint">{forecast.from??t('hubUnknown')} – {forecast.to??t('hubUnknown')} · UTC</p><p className="field-hint">{t('aiForecastCoverage',{days:forecast.completeCalendarDays})}</p><p className="field-hint">{t('aiPricingCoverage',{known:forecast.knownCalls,unknown:Math.max(0,forecast.totalCalls-forecast.knownCalls)})}</p>{key==='apiUsd'&&<p className="field-hint">{t('aiApiComparisonAssumption')}</p>}</section>})}<p className="field-hint">{t('aiForecastNotCap')}</p></section>
   <section className="ai-card"><h2>{t('aiRecentActivity')}</h2><p className="field-hint">{t('aiRecentAllTime')}</p>{usage.recent.length?<div className="ai-usage-list">{usage.recent.map((r,i)=><article key={`${r.occurredAt}-${i}`}><div><strong>{purposeLabel(r.purpose,t)}</strong><span>{t(attemptState(r))}</span></div><p>{t('aiActualModel')}: {r.actualModel??t('aiModelUnreported')} · {t(routeKey(r.route??r.provider))}</p>{r.requestedModel&&<p className="field-hint">{t('aiRequestedModel')}: {r.requestedModel}</p>}<p className="field-hint">{t('aiReportedTier')}: {r.actualServiceTier??t('hubUnknown')}</p><small>{formatDate(r.occurredAt,locale,timezone)} · {t(r.category===null?'aiUsageCategoryUnknown':r.category==='normal'?'aiNormalUse':'aiSetupTests')}</small><p>{t('aiTokenPair',{input:r.inputTokens===null?t('hubUnknown'):r.inputTokens,output:r.outputTokens===null?t('hubUnknown'):r.outputTokens})}</p>{r.errorCode&&<p className="field-hint">{t(safeError(r.errorCode))}</p>}</article>)}</div>:<p>{t('aiNoUsage')}</p>}</section>
  </aside></div>
 </section>;
}
function purposeLabel(purpose:string,t:(key:TranslationKey,values?:Record<string,string|number>)=>string){const key=purposeKey(purpose);return key?t(key):purpose}
