import { useCallback, useEffect, useRef, useState } from 'react';
import { api } from './api';
import type { Display, Membership } from './types';
import type { IntegrationConnection, IntegrationCredential } from './home-types';
import { Check, Dialog, Empty, ErrorNotice, Field, Icon, Loading, Submit, useAction, useI18n } from './ui';
import { formatDate } from './time';
export function IntegrationsPanel({member,displays}:{member:Membership;displays:Display[]}) {
 const {t,locale}=useI18n(); const base=`/households/${member.household_id}/integrations`;
 const [connections,setConnections]=useState<IntegrationConnection[]|null>(null);
 const [editor,setEditor]=useState<{mode:'create'|'credential'|'grants';connection?:IntegrationConnection}|null>(null);
 const [revoke,setRevoke]=useState<{connection:IntegrationConnection;credential?:IntegrationCredential}|null>(null);
 const [token,setToken]=useState<string|null>(null); const {run,busy,error}=useAction();
 const epoch=useRef(0);
 const refresh=useCallback(async()=>{const generation=epoch.current;try {const value=await api<{connections:IntegrationConnection[]}>(base);if(generation===epoch.current)setConnections(value.connections)}catch(error){if(generation===epoch.current&&[401,403,404].includes((error as {status:number}).status)){epoch.current++;setConnections(null);setEditor(null);setRevoke(null);setToken(null)}throw error}},[base]);
 useEffect(()=>{epoch.current++;setConnections(null);setEditor(null);setRevoke(null);setToken(null);void run(refresh);return()=>{epoch.current++}},[refresh]);
 return <><section className="section-heading"><div><p className="eyebrow">{t('integrations')}</p><h1>{t('integrationTitle')}</h1><p>{t('integrationBody')}</p></div><button className="button primary" onClick={()=>setEditor({mode:'create'})}><Icon name="plus"/>{t('integrationCreate')}</button></section><ErrorNotice error={error}/>
 {connections===null?<Loading/>:!connections.length?<Empty title={t('integrationEmpty')} body={t('integrationBody')}/>:<div className="integration-grid">{connections.map(connection=><article className="surface-card integration-card" key={connection.id}><div className="hub-panel-title"><h2>{connection.name}</h2>{connection.revokedAt&&<span className="status">{t('revoked')}</span>}</div><p className="field-hint">{t('integrationDisplays')}: {connection.displayIds.map(id=>displays.find(d=>d.id===id)?.name).filter(Boolean).join(' · ')||'—'}</p><ul className="integration-credentials">{connection.credentials.map(credential=><li key={credential.id}><div><strong>{credential.name}</strong><small>{credential.revokedAt?t('revoked'):credential.lastUsedAt?formatDate(credential.lastUsedAt,locale,member.timezone):t('integrationNever')}</small><span>{credential.capabilities.map(cap=>t(cap.endsWith('.write')?'integrationWrite':cap.endsWith('.read')?'integrationRead':'integrationDelete')).join(' · ')}</span></div>{!connection.revokedAt&&!credential.revokedAt&&<button className="text-button danger-text" onClick={()=>setRevoke({connection,credential})}>{t('integrationRevokeToken')}</button>}</li>)}</ul>{!connection.revokedAt&&<div className="card-actions"><button className="button" onClick={()=>setEditor({mode:'credential',connection})}>{t('integrationNewToken')}</button><button className="button" onClick={()=>setEditor({mode:'grants',connection})}>{t('integrationGrants')}</button><button className="text-button danger-text" onClick={()=>setRevoke({connection})}>{t('integrationRevoke')}</button></div>}</article>)}</div>}
 {editor&&<ConnectionEditor mode={editor.mode} connection={editor.connection} displays={displays} base={base} onClose={()=>setEditor(null)} onSaved={async(value)=>{setEditor(null);setToken(value??null);await refresh()}}/>}
 {token&&<Dialog title={t('integrationTokenTitle')} onClose={()=>setToken(null)}><p>{t('integrationTokenBody')}</p><Field label={t('integrationToken')}><textarea className="integration-token" readOnly value={token} rows={3} autoComplete="off" spellCheck={false} onFocus={e=>e.target.select()}/></Field><button className="button primary" onClick={()=>setToken(null)}>{t('integrationSaved')}</button></Dialog>}
 {revoke&&<Dialog title={t(revoke.credential?'integrationRevokeToken':'integrationRevoke')} onClose={()=>setRevoke(null)}><p>{t(revoke.credential?'integrationTokenRevocation':'integrationRevokeBody')}</p><ErrorNotice error={error}/><div className="form-actions"><button className="button" onClick={()=>setRevoke(null)}>{t('cancel')}</button><button className="button danger" disabled={busy} onClick={()=>void run(async()=>{await api(`${base}/${revoke.connection.id}${revoke.credential?`/credentials/${revoke.credential.id}`:''}/revoke`,'POST',{expectedRevision:revoke.credential?.revision??revoke.connection.revision});setRevoke(null);await refresh()})}>{t('integrationRevokeConfirm')}</button></div></Dialog>}
 </>;
}
function ConnectionEditor({mode,connection,displays,base,onClose,onSaved}:{mode:'create'|'credential'|'grants';connection?:IntegrationConnection;displays:Display[];base:string;onClose:()=>void;onSaved:(token?:string)=>Promise<void>}) {
 const {t}=useI18n(); const [grants,setGrants]=useState(connection?.displayIds??[]);const [caps,setCaps]=useState(['integration.items.write']);const {run,busy,error}=useAction();
 return <Dialog title={t(mode==='create'?'integrationCreate':mode==='credential'?'integrationNewToken':'integrationGrants')} onClose={onClose}><form className="form-stack" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);void run(async()=>{const credential={name:data.get('credentialName'),capabilities:caps,expiresAt:null};const result=await api<{credentialToken?:string}>(mode==='create'?base:mode==='grants'?`${base}/${connection!.id}`:`${base}/${connection!.id}/credentials`,mode==='grants'?'PATCH':'POST',mode==='create'?{name:data.get('name'),displayIds:grants,credential}:mode==='grants'?{expectedRevision:connection!.revision,displayIds:grants}:{...credential,expectedRevision:connection!.revision});await onSaved(result.credentialToken)})}}>
 {mode==='create'&&<Field label={t('integrationName')}><input name="name" required maxLength={80}/></Field>}
 {mode!=='grants'&&<><Field label={t('integrationCredential')}><input name="credentialName" required maxLength={80}/></Field><fieldset><legend>{t('integrationCapabilities')}</legend>{(['write','read','delete'] as const).map(cap=><Check key={cap} label={t(({write:'integrationWrite',read:'integrationRead',delete:'integrationDelete'} as const)[cap])} checked={caps.includes(`integration.items.${cap}`)} onChange={v=>setCaps(v?[...caps,`integration.items.${cap}`]:caps.filter(c=>c!==`integration.items.${cap}`))}/>)}</fieldset></>}
 {mode!=='credential'&&<fieldset><legend>{t('integrationDisplays')}</legend>{displays.filter(d=>!d.revoked_at).map(display=><Check key={display.id} label={display.name} checked={grants.includes(display.id)} onChange={v=>setGrants(v?[...grants,display.id]:grants.filter(id=>id!==display.id))}/>)}<p className="field-hint">{t('integrationDisplaysHint')}</p></fieldset>}
 <ErrorNotice error={error}/><div className="form-actions"><button type="button" className="button" onClick={onClose}>{t('cancel')}</button><Submit busy={busy||mode!=='grants'&&!caps.length} label={t('save')}/></div></form></Dialog>;
}
