import { useCallback, useEffect, useState } from "react";
import { api } from "./api";
import type { Display, MonitorTask, Person } from "./types";
import { ErrorNotice, Field, Icon, Loading, useI18n } from "./ui";
import { formatDate } from "./time";

interface Draft{name:string;instruction:string;sourceUrl:string;checkIntervalMinutes:number;noticeDaysBefore:number;noticeLocalTime:string;providerPolicy:'default'|'local'|'openai';modelTier:'routine'|'strong';personIds:string[];displayIds:string[];}
const empty=(displays:Display[]):Draft=>({name:"",instruction:"",sourceUrl:"",checkIntervalMinutes:1440,noticeDaysBefore:1,noticeLocalTime:"18:00",providerPolicy:'default',modelTier:'routine',personIds:[],displayIds:displays[0]?[displays[0].id]:[]});
const fromTask=(task:MonitorTask):Draft=>({name:task.name,instruction:task.instruction,sourceUrl:task.sourceUrl,checkIntervalMinutes:task.checkIntervalMinutes,noticeDaysBefore:task.noticeDaysBefore,noticeLocalTime:task.noticeLocalTime,providerPolicy:task.providerPolicy,modelTier:task.modelTier,personIds:task.targets.personIds,displayIds:task.targets.displayIds});

export function MonitorsPanel({householdId,timezone,people,displays}:{householdId:string;timezone:string;people:Person[];displays:Display[]}){
  const {t,locale}=useI18n();const base=`/households/${householdId}/monitors`;
  const [tasks,setTasks]=useState<MonitorTask[]>();const [editing,setEditing]=useState<MonitorTask|null|undefined>();const [draft,setDraft]=useState<Draft>(()=>empty(displays));const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);const [focusPreview,setFocusPreview]=useState<string>();
  const load=useCallback(async()=>{try{setTasks((await api<{tasks:MonitorTask[]}>(base)).tasks);setError(undefined);}catch(e){setError(e);}},[base]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!focusPreview||!tasks?.some((task)=>task.id===focusPreview&&task.interpretedRule))return;document.getElementById(`monitor-preview-${focusPreview}`)?.focus();setFocusPreview(undefined);},[focusPreview,tasks]);
  const submit=async()=>{setBusy(true);setError(undefined);try{const body={name:draft.name,instruction:draft.instruction,sourceUrl:draft.sourceUrl,checkIntervalMinutes:Number(draft.checkIntervalMinutes),noticeDaysBefore:Number(draft.noticeDaysBefore),noticeLocalTime:draft.noticeLocalTime,providerPolicy:draft.providerPolicy,modelTier:draft.modelTier,targets:{personIds:draft.personIds,displayIds:draft.displayIds}};if(editing)await api(`${base}/${editing.id}`,'PATCH',{...body,expectedRevision:editing.revision});else await api(base,'POST',body);setEditing(undefined);setDraft(empty(displays));await load();}catch(e){setError(e);}finally{setBusy(false);}};
  const action=async(task:MonitorTask,name:'interpret'|'approve'|'pause'|'resume')=>{setBusy(true);setError(undefined);try{await api(`${base}/${task.id}/${name}`,'POST',{expectedRevision:task.revision});if(name==='interpret')setFocusPreview(task.id);await load();}catch(e){setError(e);}finally{setBusy(false);}};
  const remove=async(task:MonitorTask)=>{setBusy(true);try{await api(`${base}/${task.id}`,'DELETE',{expectedRevision:task.revision});await load();}catch(e){setError(e);}finally{setBusy(false);}};
  const toggle=(key:'personIds'|'displayIds',id:string)=>setDraft((value)=>({...value,[key]:value[key].includes(id)?value[key].filter((item)=>item!==id):[...value[key],id]}));
  const providerLabel=(policy:MonitorTask['providerPolicy'])=>t(policy==='local'?'monitorProviderLocal':policy==='openai'?'monitorProviderOpenAi':'monitorProviderDefault');
  const lastResult=(value:string|null)=>{if(!value)return '—';if(value==='unchanged')return t('monitorResultUnchanged');if(value==='failed')return t('monitorResultFailed');const match=/^(\d+) event\(s\)$/.exec(value);return match?t('monitorResultEvents',{count:Number(match[1])}):value;};
  const list=(values:string[])=>values.length?values.join(', '):t('monitorRuleNone');
  const targetNames=(task:MonitorTask)=>[...people.filter((person)=>task.targets.personIds.includes(person.id)).map((person)=>person.display_name),...displays.filter((display)=>task.targets.displayIds.includes(display.id)).map((display)=>display.name)].join(', ')||t('monitorRuleNone');
  if(!tasks)return <><ErrorNotice error={error}/><Loading/></>;
  return <section className="monitor-page" aria-labelledby="monitor-title">
    <header className="section-heading"><div><p className="eyebrow">{t('monitorEyebrow')}</p><h1 id="monitor-title">{t('monitors')}</h1><p>{t('monitorBody')}</p></div><button className="button primary" onClick={()=>{setEditing(null);setDraft(empty(displays));}}><Icon name="plus"/>{t('monitorNew')}</button></header>
    <ErrorNotice error={error}/>
    {editing!==undefined&&<form className="surface-card form-stack monitor-form" onSubmit={(e)=>{e.preventDefault();void submit();}}>
      <h2>{editing?t('monitorEdit'):t('monitorQuestion')}</h2>
      <Field label={t('monitorName')}><input required maxLength={80} value={draft.name} onChange={(e)=>setDraft({...draft,name:e.target.value})}/></Field>
      <Field label={t('monitorInstruction')} hint={t('monitorInstructionHint')}><textarea required minLength={10} maxLength={2000} rows={4} value={draft.instruction} onChange={(e)=>setDraft({...draft,instruction:e.target.value})}/></Field>
      <Field label={t('monitorSource')}><input required type="url" value={draft.sourceUrl} onChange={(e)=>setDraft({...draft,sourceUrl:e.target.value})}/></Field>
      <div className="form-grid"><Field label={t('monitorFrequency')}><select value={draft.checkIntervalMinutes} onChange={(e)=>setDraft({...draft,checkIntervalMinutes:Number(e.target.value)})}><option value={60}>{t('monitorHourly')}</option><option value={360}>{t('monitorSixHours')}</option><option value={1440}>{t('monitorDaily')}</option><option value={10080}>{t('monitorWeekly')}</option></select></Field><Field label={t('monitorDaysBefore')}><input type="number" min={0} max={30} required value={draft.noticeDaysBefore} onChange={(e)=>setDraft({...draft,noticeDaysBefore:Number(e.target.value)})}/></Field><Field label={t('monitorNotice')}><input type="time" required value={draft.noticeLocalTime} onChange={(e)=>setDraft({...draft,noticeLocalTime:e.target.value})}/></Field></div>
      <div className="form-grid"><Field label={t('monitorProvider')}><select value={draft.providerPolicy} onChange={(e)=>setDraft({...draft,providerPolicy:e.target.value as Draft['providerPolicy']})}><option value="default">{t('monitorProviderDefault')}</option><option value="local">{t('monitorProviderLocal')}</option><option value="openai">{t('monitorProviderOpenAi')}</option></select></Field><Field label={t('monitorModel')}><select value={draft.modelTier} onChange={(e)=>setDraft({...draft,modelTier:e.target.value as Draft['modelTier']})}><option value="routine">{t('aiRoutineModel')}</option><option value="strong">{t('aiStrongModel')}</option></select></Field></div>
      <p className="monitor-stats">{t('monitorProviderHint')}</p>
      <fieldset><legend>{t('monitorRecipients')}</legend><div className="monitor-targets">{people.map((p)=><label key={p.id}><input type="checkbox" checked={draft.personIds.includes(p.id)} onChange={()=>toggle('personIds',p.id)}/>{p.display_name}</label>)}{displays.map((d)=><label key={d.id}><input type="checkbox" checked={draft.displayIds.includes(d.id)} onChange={()=>toggle('displayIds',d.id)}/>{d.name}</label>)}</div></fieldset>
      <div className="card-actions"><button className="button primary" disabled={busy||(!draft.personIds.length&&!draft.displayIds.length)}>{t('save')}</button><button type="button" className="button" onClick={()=>setEditing(undefined)}>{t('cancel')}</button></div>
    </form>}
    <div className="monitor-grid">{tasks.map((task)=><article className="surface-card monitor-card" key={task.id}>
      <div className="card-top"><div><h2>{task.name}</h2><small>{task.sourceUrl}</small></div><span className={`monitor-state ${task.state}`}>{t(`monitorState${task.state[0]!.toUpperCase()}${task.state.slice(1)}` as 'monitorStateDraft')}</span></div>
      <p>{task.instruction}</p>{task.interpretedRule&&<div className="preview-panel" id={`monitor-preview-${task.id}`} tabIndex={-1} role="status" aria-live="polite" aria-labelledby={`monitor-preview-title-${task.id}`}><p className="eyebrow" id={`monitor-preview-title-${task.id}`}>{t('monitorInterpretation')}</p><strong>{task.interpretedRule.summary}</strong><dl className="monitor-rule"><div><dt>{t('monitorRuleEventTypes')}</dt><dd>{list(task.interpretedRule.eventTypes)}</dd></div><div><dt>{t('monitorRuleKeywords')}</dt><dd>{list(task.interpretedRule.keywords)}</dd></div><div><dt>{t('monitorRulePeople')}</dt><dd>{list(task.interpretedRule.people)}</dd></div><div><dt>{t('monitorRuleSchedule')}</dt><dd>{t('monitorRuleScheduleValue',{minutes:task.checkIntervalMinutes})}</dd></div><div><dt>{t('monitorRuleNotice')}</dt><dd>{t('monitorRuleNoticeValue',{days:task.noticeDaysBefore,time:task.noticeLocalTime,timezone})}</dd></div><div><dt>{t('monitorRuleTargets')}</dt><dd>{targetNames(task)}</dd></div></dl><p>{t('monitorApprovalHint')}</p></div>}
      {task.events.length>0&&<details className="monitor-findings"><summary>{t('monitorFindings',{count:task.events.length})}</summary>{task.events.map((event,index)=><div key={`${event.date}:${event.type}:${index}`}><strong>{event.date}{event.time?` ${event.time.slice(0,5)}`:''} · {event.description}</strong><blockquote>{event.evidence.quote}</blockquote><a href={event.evidence.sourceUrl} target="_blank" rel="noreferrer">{t('monitorOpenSource')}</a><small>{t('monitorConfidence',{value:Math.round(event.confidence*100)})}{event.uncertainty?` · ${event.uncertainty}`:''}</small></div>)}</details>}
      <dl className="monitor-meta"><div><dt>{t('monitorProvider')}</dt><dd>{providerLabel(task.providerPolicy)}</dd></div><div><dt>{t('monitorNext')}</dt><dd>{task.nextCheckAt?formatDate(task.nextCheckAt,locale,timezone):'—'}</dd></div><div><dt>{t('monitorLastCheck')}</dt><dd>{task.lastCheckedAt?formatDate(task.lastCheckedAt,locale,timezone):'—'}</dd></div><div><dt>{t('monitorLastChange')}</dt><dd>{task.lastChangedAt?formatDate(task.lastChangedAt,locale,timezone):'—'}</dd></div><div><dt>{t('monitorLastResult')}</dt><dd>{task.errorCode?t(task.errorCode as 'INTERNAL_ERROR'):lastResult(task.lastResult)}</dd></div></dl>
      <p className="monitor-stats">{t('monitorStats',{checks:task.stats.checks,ai:task.stats.aiCalls})}</p>
      <div className="card-actions"><button disabled={busy} onClick={()=>{setEditing(task);setDraft(fromTask(task));}}>{t('edit')}</button>{task.state==='draft'&&!task.interpretedRule&&<button disabled={busy} onClick={()=>void action(task,'interpret')}>{t('monitorInterpret')}</button>}{task.state==='draft'&&task.interpretedRule&&<button disabled={busy} onClick={()=>void action(task,'approve')}>{t('monitorApprove')}</button>}{task.state==='active'&&<button disabled={busy} onClick={()=>void action(task,'pause')}>{t('monitorPause')}</button>}{task.state==='paused'&&<button disabled={busy} onClick={()=>void action(task,'resume')}>{t('monitorResume')}</button>}<button disabled={busy} onClick={()=>void remove(task)}>{t('delete')}</button></div>
    </article>)}</div>
    {!tasks.length&&<p className="surface-card">{t('monitorEmpty')}</p>}
  </section>;
}
