import { randomUUID } from 'node:crypto';
import type { AiModelTier, MonitorProviderPolicy } from '@samvev/contracts';
import { DomainError } from '@samvev/core';
import { pool, transaction } from '../db.ts';
import { AiAdminService } from '../ai/admin-service.ts';
import { MonitorSourceFetcher, selectRelevantSource, type SourceDocument } from './source-fetcher.ts';
import { extractionFromAi, withdrawMonitorMessages } from './service.ts';
import { monitorEventKey, orderedMonitorEvents } from './event-identity.ts';

interface ClaimedTask {id:string;household_id:string;owner_membership_id:string;instruction:string;source_url:string;check_interval_minutes:number;notice_days_before:number;notice_local_time:string;provider_policy:MonitorProviderPolicy;model_tier:AiModelTier;interpreted_rule:unknown;revision:number;lease_token:string;last_processed_fingerprint:string|null;owner_authorized:boolean;}
export interface MonitorBatchResult {claimed:number;changed:number;unchanged:number;failed:number;}

async function claimOne():Promise<ClaimedTask|undefined>{return transaction(async(client)=>{const row=(await client.query<Omit<ClaimedTask,'lease_token'>>(`SELECT t.id,t.household_id,t.owner_membership_id,t.instruction,t.source_url,t.check_interval_minutes,t.notice_days_before,t.notice_local_time::text,t.provider_policy,t.model_tier,t.interpreted_rule,t.revision,t.last_processed_fingerprint,EXISTS(SELECT 1 FROM memberships m JOIN accounts a ON a.id=m.account_id AND a.disabled_at IS NULL WHERE m.id=t.owner_membership_id AND m.household_id=t.household_id AND m.capabilities ? 'household.manage' AND m.capabilities ? 'message.create.household' AND m.capabilities ? 'message.schedule' AND (NOT EXISTS(SELECT 1 FROM monitor_task_display_targets d WHERE d.task_id=t.id) OR m.capabilities ? 'message.publish.display')) AS owner_authorized FROM monitor_tasks t WHERE t.state='active' AND t.approved_revision=t.revision AND t.next_check_at<=clock_timestamp() AND (t.lease_expires_at IS NULL OR t.lease_expires_at<clock_timestamp()) ORDER BY t.next_check_at,t.id FOR UPDATE OF t SKIP LOCKED LIMIT 1`)).rows[0];if(!row)return undefined;const token=randomUUID();await client.query(`UPDATE monitor_tasks SET lease_token=$2,lease_expires_at=clock_timestamp()+interval '2 minutes' WHERE id=$1`,[row.id,token]);return {...row,lease_token:token};});}

function errorCode(error:unknown):string{return error instanceof DomainError?error.code:'AI_UPSTREAM_ERROR';}
async function stillOwned(task:ClaimedTask):Promise<boolean>{const result=await pool.query(`SELECT 1 FROM monitor_tasks WHERE id=$1 AND state='active' AND revision=$2 AND approved_revision=revision AND lease_token=$3`,[task.id,task.revision,task.lease_token]);return Boolean(result.rowCount);}
async function pauseUnauthorized(task:ClaimedTask):Promise<boolean>{return transaction(async(client)=>{const updated=await client.query(`UPDATE monitor_tasks SET state='paused',revision=revision+1,next_check_at=NULL,last_processed_fingerprint=NULL,check_count=check_count+1,last_checked_at=clock_timestamp(),last_result='failed',error_code='MONITOR_OWNER_UNAUTHORIZED',lease_token=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE id=$1 AND revision=$2 AND lease_token=$3 RETURNING id`,[task.id,task.revision,task.lease_token]);if(!updated.rowCount)return false;await withdrawMonitorMessages(client,task.id);await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,error_code,ai_called) VALUES($1,$2,'failed','MONITOR_OWNER_UNAUTHORIZED',false)`,[task.id,task.revision]);return true;});}
async function finishFailure(task:ClaimedTask,error:unknown,aiCalled:boolean):Promise<boolean>{return transaction(async(client)=>{const updated=await client.query(`UPDATE monitor_tasks SET check_count=check_count+1,ai_call_count=ai_call_count+$6::int,last_checked_at=clock_timestamp(),next_check_at=clock_timestamp()+($4||' minutes')::interval,error_code=$5,last_result='failed',lease_token=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE id=$1 AND revision=$2 AND lease_token=$3 RETURNING id`,[task.id,task.revision,task.lease_token,task.check_interval_minutes,errorCode(error),aiCalled?1:0]);if(!updated.rowCount)return false;await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,error_code,ai_called) VALUES($1,$2,'failed',$3,$4)`,[task.id,task.revision,errorCode(error),aiCalled]);return true;});}

async function finishUnchanged(task:ClaimedTask,source:SourceDocument):Promise<boolean>{return transaction(async(client)=>{const updated=await client.query(`UPDATE monitor_tasks SET check_count=check_count+1,unchanged_count=unchanged_count+1,last_checked_at=clock_timestamp(),next_check_at=clock_timestamp()+($4||' minutes')::interval,last_result='unchanged',error_code=NULL,source_final_url=$5,source_content_type=$6,source_etag=$7,source_last_modified=$8,lease_token=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE id=$1 AND revision=$2 AND lease_token=$3 RETURNING id`,[task.id,task.revision,task.lease_token,task.check_interval_minutes,source.finalUrl,source.contentType,source.etag??null,source.lastModified??null]);if(!updated.rowCount)return false;await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,fingerprint,ai_called) VALUES($1,$2,'unchanged',$3,false)`,[task.id,task.revision,source.fingerprint]);return true;});}

function messageBody(event:{date:string;time:string|null;description:string;actions:string[]}):string{const when=`${event.date}${event.time?` ${event.time}`:''}`;const actions=event.actions.length?` · ${event.actions.join(' · ')}`:'';return `${event.description}${actions} · ${when}`.slice(0,1000);}

async function reconcile(task:ClaimedTask,source:SourceDocument,events:ReturnType<typeof extractionFromAi>['events'],provider:string,model:string):Promise<boolean>{return transaction(async(client)=>{
  const owned=await client.query(`SELECT 1 FROM monitor_tasks WHERE id=$1 AND state='active' AND revision=$2 AND approved_revision=revision AND lease_token=$3 FOR UPDATE`,[task.id,task.revision,task.lease_token]);if(!owned.rowCount){await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,fingerprint,ai_called,provider,model) VALUES($1,$2,'superseded',$3,true,$4,$5)`,[task.id,task.revision,source.fingerprint,provider,model]);return false;}
  const targets=await Promise.all([client.query<{person_id:string}>('SELECT person_id FROM monitor_task_person_targets WHERE task_id=$1',[task.id]),client.query<{display_id:string}>('SELECT display_id FROM monitor_task_display_targets WHERE task_id=$1',[task.id])]);
  const currentKeys=new Set<string>();
  for(const event of orderedMonitorEvents(events)){
    const key=monitorEventKey(task.id,event.eventKeyPart);currentKeys.add(key);
    const timing=(await client.query<{publish_at:Date;expires_at:Date}>(`SELECT ((($1::date-$2::int)+$3::time) AT TIME ZONE h.timezone) AS publish_at,(($1::date+1)::timestamp AT TIME ZONE h.timezone) AS expires_at FROM households h WHERE h.id=$4`,[event.date,task.notice_days_before,task.notice_local_time,task.household_id])).rows[0]!;
    const existing=(await client.query<{id:string;message_id:string|null}>(`SELECT id,message_id FROM monitor_events WHERE task_id=$1 AND event_key=$2 FOR UPDATE`,[task.id,key])).rows[0];
    let messageId=existing?.message_id??null;const body=messageBody(event);
    if(timing.expires_at>new Date()){
      if(messageId){const message=(await client.query<{state:string;revision:number}>('SELECT state,revision FROM messages WHERE id=$1 FOR UPDATE',[messageId])).rows[0];if(message&&['scheduled','published'].includes(message.state)){await client.query(`UPDATE messages SET body=$2,publish_at=CASE WHEN state='scheduled' THEN $3 ELSE publish_at END,expires_at=$4,revision=revision+1,updated_at=clock_timestamp() WHERE id=$1`,[messageId,body,timing.publish_at,timing.expires_at]);await client.query(`UPDATE message_display_targets SET delivery_state='queued',delivered_revision=NULL,delivered_at=NULL,displayed_at=NULL WHERE message_id=$1 AND delivery_state<>'cancelled'`,[messageId]);await client.query(`INSERT INTO message_lifecycle_events(message_id,from_state,to_state,revision,actor_type,idempotency_key) VALUES($1,$2,$2,$3,'worker',$4) ON CONFLICT DO NOTHING`,[messageId,message.state,message.revision+1,`monitor-update:${task.id}:${key}:${source.fingerprint}`]);}else messageId=null;}
      if(!messageId){const state=timing.publish_at>new Date()?'scheduled':'published';const inserted=await client.query<{id:string}>(`INSERT INTO messages(household_id,author_membership_id,body,importance,audience_household,publish_at,expires_at,state,idempotency_key,published_at) VALUES($1,$2,$3,'normal',false,$4,$5,$6,$7,CASE WHEN $6='published' THEN clock_timestamp() END) RETURNING id`,[task.household_id,task.owner_membership_id,body,timing.publish_at,timing.expires_at,state,`monitor:${task.id}:${key}:${source.fingerprint.slice(0,12)}`]);messageId=inserted.rows[0]!.id;for(const row of targets[0].rows)await client.query(`INSERT INTO message_person_audiences(household_id,message_id,person_id) VALUES($1,$2,$3)`,[task.household_id,messageId,row.person_id]);for(const row of targets[1].rows)await client.query(`INSERT INTO message_display_targets(household_id,message_id,display_id,delivery_state) VALUES($1,$2,$3,'queued')`,[task.household_id,messageId,row.display_id]);await client.query(`INSERT INTO message_lifecycle_events(message_id,to_state,revision,actor_type,idempotency_key) VALUES($1,$2,1,'worker',$3)`,[messageId,state,`monitor-create:${task.id}:${key}:${source.fingerprint.slice(0,12)}`]);}
    }
    const values=[task.household_id,task.id,key,event.date,event.time,event.type,event.description,JSON.stringify(event.actions),JSON.stringify(event.who),JSON.stringify(event.evidence),event.confidence,event.uncertainty,source.fingerprint,messageId];
    await client.query(`INSERT INTO monitor_events(household_id,task_id,event_key,event_date,event_time,event_type,description,actions,applies_to,evidence,confidence,uncertainty,source_fingerprint,message_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(task_id,event_key) DO UPDATE SET event_date=EXCLUDED.event_date,event_time=EXCLUDED.event_time,event_type=EXCLUDED.event_type,description=EXCLUDED.description,actions=EXCLUDED.actions,applies_to=EXCLUDED.applies_to,evidence=EXCLUDED.evidence,confidence=EXCLUDED.confidence,uncertainty=EXCLUDED.uncertainty,source_fingerprint=EXCLUDED.source_fingerprint,message_id=COALESCE(EXCLUDED.message_id,monitor_events.message_id),active=true,updated_at=clock_timestamp()`,values);
  }
  const removed=await client.query<{id:string;message_id:string|null}>(`UPDATE monitor_events SET active=false,updated_at=clock_timestamp() WHERE task_id=$1 AND active=true AND NOT(event_key=ANY($2::text[])) RETURNING id,message_id`,[task.id,[...currentKeys]]);
  for(const event of removed.rows){if(!event.message_id)continue;const message=(await client.query<{state:string;revision:number}>('SELECT state,revision FROM messages WHERE id=$1 FOR UPDATE',[event.message_id])).rows[0];if(message&&['scheduled','published'].includes(message.state)){const next=message.state==='scheduled'?'cancelled':'withdrawn';await client.query(`UPDATE messages SET state=$2,revision=revision+1,ended_at=clock_timestamp(),updated_at=clock_timestamp() WHERE id=$1`,[event.message_id,next]);await client.query(`UPDATE message_display_targets SET delivery_state='cancelled' WHERE message_id=$1`,[event.message_id]);await client.query(`INSERT INTO message_lifecycle_events(message_id,from_state,to_state,revision,actor_type,idempotency_key) VALUES($1,$2,$3,$4,'worker',$5)`,[event.message_id,message.state,next,message.revision+1,`monitor-remove:${task.id}:${event.id}:${source.fingerprint}`]);}}
  await client.query(`UPDATE monitor_tasks SET check_count=check_count+1,ai_call_count=ai_call_count+1,last_checked_at=clock_timestamp(),next_check_at=clock_timestamp()+($4||' minutes')::interval,last_result=$5,last_changed_at=clock_timestamp(),error_code=NULL,source_final_url=$6,source_content_type=$7,source_etag=$8,source_last_modified=$9,last_processed_fingerprint=$10,lease_token=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE id=$1 AND revision=$2 AND lease_token=$3`,[task.id,task.revision,task.lease_token,task.check_interval_minutes,`${events.length} event(s)`,source.finalUrl,source.contentType,source.etag??null,source.lastModified??null,source.fingerprint]);
  await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,fingerprint,ai_called,provider,model) VALUES($1,$2,'changed',$3,true,$4,$5)`,[task.id,task.revision,source.fingerprint,provider,model]);return true;
});}

export class MonitorEngine{
  constructor(private readonly fetcher=new MonitorSourceFetcher(),private readonly ai=new AiAdminService()){}
  async runOnce():Promise<'idle'|'changed'|'unchanged'|'failed'|'superseded'>{const task=await claimOne();if(!task)return'idle';if(!task.owner_authorized)return await pauseUnauthorized(task)?'failed':'superseded';let aiCalled=false;try{const fetched=await this.fetcher.fetch(task.source_url);const source=selectRelevantSource(fetched,task.interpreted_rule);if(!(await stillOwned(task)))return'superseded';if(source.fingerprint===task.last_processed_fingerprint)return await finishUnchanged(task,source)?'unchanged':'superseded';const input=`Return only JSON matching {"version":1,"events":[{"date":"YYYY-MM-DD","time":"HH:MM or null","type":"string","description":"string","actions":["string"],"who":["string"],"evidence":{"quote":"exact quote","sourceUrl":"${source.finalUrl}"},"confidence":0.0,"uncertainty":"string or null"}]}. Extract only future events relevant to this rule. Never infer missing dates or facts. Evidence quote must occur verbatim in the source. Rule: ${JSON.stringify(task.interpreted_rule)}\nInstruction: ${task.instruction}\nSource:\n${source.text}`;aiCalled=true;const outcome=await this.ai.executeTaskWithContext(task.household_id,{operation:'extract',purpose:'monitor_source_analysis',input,modelTier:task.model_tier,maxOutputTokens:4096,sources:[{url:source.finalUrl,observedAt:new Date().toISOString(),uncertainty:'unknown'}]},task.provider_policy);const extracted=extractionFromAi(outcome.result.output,source);return await reconcile(task,source,extracted.events,outcome.provider,outcome.model)?'changed':'superseded';}catch(error){return await finishFailure(task,error,aiCalled)?'failed':'superseded';}}
}
export async function runMonitorBatch(limit=5,engine=new MonitorEngine()):Promise<MonitorBatchResult>{const result={claimed:0,changed:0,unchanged:0,failed:0};for(let i=0;i<limit;i++){const outcome=await engine.runOnce();if(outcome==='idle')break;result.claimed++;if(outcome==='changed')result.changed++;else if(outcome==='unchanged')result.unchanged++;else if(outcome==='failed')result.failed++;}return result;}
