import { randomUUID } from 'node:crypto';
import type { AiModelTier, MonitorProviderPolicy } from '@samvev/contracts';
import { DomainError } from '@samvev/core';
import { pool, transaction, type DbClient } from '../db.ts';
import { AiAdminService } from '../ai/admin-service.ts';
import { MONITOR_AGENT_DEADLINE_MS, MONITOR_LEASE_MS, MonitorAgentRunner, monitorDependencyFingerprint, type MonitorAgentResult, type MonitorDependency, type MonitorToolAttempt, type MonitorToolProvenance } from './agent-runner.ts';
import { MonitorSourceFetcher, normalizeMonitorUrl, selectRelevantSource, type SourceDocument } from './source-fetcher.ts';
import { answerFromAi, extractionFromAi, type MonitorActor, validateMonitorTargets, withdrawMonitorMessages } from './service.ts';
import { monitorEventKey, orderedMonitorEvents } from './event-identity.ts';

type MonitorRunKind='scheduled'|'test'|'manual'|'smarter';
interface ClaimedTask {id:string;household_id:string;owner_membership_id:string;initiating_membership_id?:string;instruction:string;source_url:string;state:'draft'|'active'|'paused';check_interval_minutes:number;notice_days_before:number;notice_local_time:string;provider_policy:MonitorProviderPolicy;model_tier:AiModelTier;interpreted_rule:any;revision:number;lease_token:string;last_processed_fingerprint:string|null;source_dependency_manifest:MonitorDependency[];next_check_at:Date|null;owner_authorized:boolean;}
type Analysis={kind:'events';value:ReturnType<typeof extractionFromAi>}|{kind:'answer';value:ReturnType<typeof answerFromAi>};
interface RunMeta {aiCalls:number;attemptedTools:number;provider:string|null;model:string|null;provenance:MonitorToolProvenance[];attempts:MonitorToolAttempt[];dependencies:MonitorDependency[];fingerprint:string;}
export interface MonitorBatchResult {claimed:number;changed:number;unchanged:number;failed:number;}
export interface MonitorRunResult {outcome:'changed'|'unchanged';resultKind:'events'|'answer'|null;result:unknown;sourceUrl:string;checkedAt:string;sources:Array<{sourceUrl:string;fetchedAt:string}>;}
function publicSources(provenance:MonitorToolProvenance[]):Array<{sourceUrl:string;fetchedAt:string}>{const seen=new Set<string>();return provenance.filter((item)=>{if(seen.has(item.finalUrl))return false;seen.add(item.finalUrl);return true;}).map((item)=>({sourceUrl:item.finalUrl,fetchedAt:item.fetchedAt}));}

const taskColumns=`t.id,t.household_id,t.owner_membership_id,t.instruction,t.source_url,t.state,t.check_interval_minutes,t.notice_days_before,t.notice_local_time::text,t.provider_policy,t.model_tier,t.interpreted_rule,t.revision,t.last_processed_fingerprint,t.source_dependency_manifest,t.next_check_at,EXISTS(SELECT 1 FROM memberships m JOIN accounts a ON a.id=m.account_id AND a.disabled_at IS NULL WHERE m.id=t.owner_membership_id AND m.household_id=t.household_id AND m.capabilities ? 'household.manage' AND m.capabilities ? 'message.create.household' AND m.capabilities ? 'message.schedule' AND (NOT EXISTS(SELECT 1 FROM monitor_task_display_targets d WHERE d.task_id=t.id) OR (m.capabilities ? 'message.publish.display' AND (m.capabilities ? 'display.manage' OR NOT EXISTS(SELECT 1 FROM monitor_task_display_targets d WHERE d.task_id=t.id AND NOT EXISTS(SELECT 1 FROM membership_display_grants g WHERE g.household_id=t.household_id AND g.membership_id=m.id AND g.display_id=d.display_id)))))) AS owner_authorized`;

async function claimOne():Promise<ClaimedTask|undefined>{return transaction(async(client)=>{const row=(await client.query<Omit<ClaimedTask,'lease_token'>>(`SELECT ${taskColumns} FROM monitor_tasks t WHERE t.state='active' AND t.approved_revision=t.revision AND t.next_check_at<=clock_timestamp() AND (t.lease_expires_at IS NULL OR t.lease_expires_at<clock_timestamp()) ORDER BY t.next_check_at,t.id FOR UPDATE OF t SKIP LOCKED LIMIT 1`)).rows[0];if(!row)return undefined;const token=randomUUID();await client.query(`UPDATE monitor_tasks SET lease_token=$2,lease_expires_at=clock_timestamp()+($3::int*interval '1 millisecond') WHERE id=$1`,[row.id,token,MONITOR_LEASE_MS]);return {...row,lease_token:token};});}

async function claimManual(actor:MonitorActor,id:string,expectedRevision:number,kind:Exclude<MonitorRunKind,'scheduled'>):Promise<ClaimedTask>{
  return transaction(async(client)=>{
    const allowed=kind==='manual'?['active']:kind==='test'?['draft','paused']:['draft','active','paused'];
    const row=(await client.query<Omit<ClaimedTask,'lease_token'>>(`SELECT ${taskColumns} FROM monitor_tasks t WHERE t.id=$1 AND t.household_id=$2 FOR UPDATE OF t`,[id,actor.householdId])).rows[0];
    if(!row)throw new DomainError('NOT_FOUND',404);if(row.revision!==expectedRevision)throw new DomainError('REVISION_CONFLICT',409);if(!allowed.includes(row.state))throw new DomainError('CONFLICT',409);
    if(kind==='manual'){const [people,displays]=await Promise.all([client.query<{person_id:string}>('SELECT person_id FROM monitor_task_person_targets WHERE task_id=$1',[id]),client.query<{display_id:string}>('SELECT display_id FROM monitor_task_display_targets WHERE task_id=$1',[id])]);await validateMonitorTargets(client,actor,{personIds:people.rows.map((item)=>item.person_id),displayIds:displays.rows.map((item)=>item.display_id)});}
    if(!row.interpreted_rule)throw new DomainError('MONITOR_INTERPRETATION_INVALID',422);
    const token=randomUUID();const claimed=await client.query(`UPDATE monitor_tasks SET lease_token=$3,lease_expires_at=clock_timestamp()+($4::int*interval '1 millisecond') WHERE id=$1 AND household_id=$2 AND (lease_expires_at IS NULL OR lease_expires_at<clock_timestamp()) RETURNING id`,[id,actor.householdId,token,MONITOR_LEASE_MS]);
    if(!claimed.rowCount)throw new DomainError('CONFLICT',409);return {...row,lease_token:token,initiating_membership_id:kind==='manual'?actor.membershipId:undefined};
  });
}

function errorCode(error:unknown):string{return error instanceof DomainError?error.code:'AI_UPSTREAM_ERROR';}
function errorStatus(code:string):number {if(code==='AI_TIMEOUT'||code==='MONITOR_SOURCE_TIMEOUT')return 504;if(code==='MONITOR_SOURCE_TOO_LARGE')return 413;if(['AI_CONFIGURATION_INVALID','AI_DISABLED','AI_ENDPOINT_BLOCKED','MONITOR_SOURCE_UNSUPPORTED','MONITOR_TOOL_INVALID','MONITOR_TOOL_LIMIT'].includes(code))return 422;return 502;}
function failureMeta(error:unknown):RunMeta{const details=error instanceof DomainError?error.details:undefined;const dependencies=Array.isArray(details?.dependencies)?details.dependencies as MonitorDependency[]:[];return{aiCalls:Number.isInteger(details?.aiCalls)?Number(details!.aiCalls):0,attemptedTools:Number.isInteger(details?.attemptedToolCount)?Number(details!.attemptedToolCount):0,provider:null,model:null,provenance:Array.isArray(details?.provenance)?details.provenance as MonitorToolProvenance[]:[],attempts:Array.isArray(details?.attempts)?details.attempts as MonitorToolAttempt[]:[],dependencies,fingerprint:dependencies.length?monitorDependencyFingerprint(dependencies):''};}
function auditErrorCode(error:unknown):string{const code=errorCode(error);return/^[A-Z][A-Z0-9_]{1,63}$/.test(code)?code:'AI_UPSTREAM_ERROR';}
async function writeToolAudit(client:DbClient,task:Pick<ClaimedTask,'id'|'revision'>,phase:MonitorRunKind|'interpretation',outcome:'success'|'failed',meta:RunMeta,error:unknown=null):Promise<void>{await client.query(`INSERT INTO monitor_tool_audits(task_id,task_revision,phase,outcome,error_code,ai_call_count,attempted_tool_count,tool_count,provenance,attempts) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[task.id,task.revision,phase,outcome,outcome==='failed'?auditErrorCode(error):null,meta.aiCalls,meta.attemptedTools,meta.provenance.length,JSON.stringify(outcome==='failed'?[]:meta.provenance),JSON.stringify(meta.attempts)]);}
async function stillOwned(task:ClaimedTask,stateRequired:boolean):Promise<boolean>{const result=await pool.query(`SELECT 1 FROM monitor_tasks WHERE id=$1 AND revision=$2 AND lease_token=$3 ${stateRequired?"AND state='active' AND approved_revision=revision":''}`,[task.id,task.revision,task.lease_token]);return Boolean(result.rowCount);}
async function membershipCanExecute(client:DbClient,task:ClaimedTask,membershipId:string):Promise<boolean>{const member=(await client.query<{capabilities:string[]}>(`SELECT m.capabilities FROM memberships m JOIN accounts a ON a.id=m.account_id AND a.disabled_at IS NULL WHERE m.id=$1 AND m.household_id=$2 FOR SHARE OF m,a`,[membershipId,task.household_id])).rows[0];if(!member)return false;const capabilities=member.capabilities;if(!['household.manage','message.create.household','message.schedule'].every((capability)=>capabilities.includes(capability)))return false;const displayTargets=await client.query<{display_id:string}>(`SELECT d.display_id FROM monitor_task_display_targets d JOIN displays target ON target.id=d.display_id AND target.household_id=d.household_id AND target.revoked_at IS NULL WHERE d.task_id=$1 FOR SHARE OF target`,[task.id]);const expectedDisplays=await client.query<{count:number}>('SELECT count(*)::int AS count FROM monitor_task_display_targets WHERE task_id=$1',[task.id]);if(displayTargets.rowCount!==(expectedDisplays.rows[0]?.count??0))return false;if(!displayTargets.rowCount)return true;if(!capabilities.includes('message.publish.display'))return false;if(capabilities.includes('display.manage'))return true;const grants=await client.query<{display_id:string}>(`SELECT g.display_id FROM membership_display_grants g WHERE g.household_id=$1 AND g.membership_id=$2 AND g.display_id=ANY($3::uuid[]) FOR SHARE`,[task.household_id,membershipId,displayTargets.rows.map((row)=>row.display_id)]);return grants.rowCount===displayTargets.rowCount;}
async function finalAuthorization(client:DbClient,task:ClaimedTask):Promise<{owner:boolean;actor:boolean}>{const owner=await membershipCanExecute(client,task,task.owner_membership_id);const actor=!task.initiating_membership_id||task.initiating_membership_id===task.owner_membership_id?owner:await membershipCanExecute(client,task,task.initiating_membership_id);return{owner,actor};}
async function rejectFinalAuthorization(client:DbClient,task:ClaimedTask,kind:'scheduled'|'manual',ownerValid:boolean,meta:RunMeta):Promise<void>{const outcome=ownerValid?'superseded':'failed';if(!ownerValid){await client.query(`UPDATE monitor_tasks SET state='paused',revision=revision+1,next_check_at=NULL,last_processed_fingerprint=NULL,source_dependency_manifest='[]'::jsonb,check_count=check_count+1,ai_call_count=ai_call_count+$4::int,last_checked_at=clock_timestamp(),last_result='failed',error_code='MONITOR_OWNER_UNAUTHORIZED',lease_token=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE id=$1 AND revision=$2 AND lease_token=$3`,[task.id,task.revision,task.lease_token,meta.aiCalls]);await withdrawMonitorMessages(client,task.id);}else await client.query(`UPDATE monitor_tasks SET lease_token=NULL,lease_expires_at=NULL WHERE id=$1 AND revision=$2 AND lease_token=$3`,[task.id,task.revision,task.lease_token]);await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,error_code,ai_called,ai_call_count,provider,model,run_kind,tool_provenance,dependency_manifest) VALUES($1,$2,$3,'MONITOR_OWNER_UNAUTHORIZED',$4,$5,$6,$7,$8,$9,$10)`,[task.id,task.revision,outcome,meta.aiCalls>0,meta.aiCalls,meta.provider,meta.model,kind,JSON.stringify([]),JSON.stringify([])]);if(meta.aiCalls||meta.attemptedTools)await writeToolAudit(client,task,kind,'failed',meta,new DomainError('MONITOR_OWNER_UNAUTHORIZED',403));}
async function pauseUnauthorized(task:ClaimedTask):Promise<boolean>{return transaction(async(client)=>{const updated=await client.query(`UPDATE monitor_tasks SET state='paused',revision=revision+1,next_check_at=NULL,last_processed_fingerprint=NULL,source_dependency_manifest='[]'::jsonb,check_count=check_count+1,last_checked_at=clock_timestamp(),last_result='failed',error_code='MONITOR_OWNER_UNAUTHORIZED',lease_token=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE id=$1 AND revision=$2 AND lease_token=$3 RETURNING id`,[task.id,task.revision,task.lease_token]);if(!updated.rowCount)return false;await withdrawMonitorMessages(client,task.id);await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,error_code,ai_called,ai_call_count,run_kind) VALUES($1,$2,'failed','MONITOR_OWNER_UNAUTHORIZED',false,0,'scheduled')`,[task.id,task.revision]);return true;});}

async function finishFailure(task:ClaimedTask,error:unknown,meta:RunMeta,kind:MonitorRunKind):Promise<boolean>{return transaction(async(client)=>{
  if(kind==='test'||kind==='smarter'){
    const updated=await client.query(`UPDATE monitor_tasks SET lease_token=NULL,lease_expires_at=NULL WHERE id=$1 AND revision=$2 AND lease_token=$3 RETURNING id`,[task.id,task.revision,task.lease_token]);if(!updated.rowCount)return false;
  }else{
    const updated=await client.query(`UPDATE monitor_tasks SET check_count=check_count+1,ai_call_count=ai_call_count+$6::int,last_checked_at=clock_timestamp(),next_check_at=CASE WHEN $7='scheduled' THEN clock_timestamp()+($4||' minutes')::interval ELSE $8 END,error_code=$5,last_result='failed',lease_token=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE id=$1 AND revision=$2 AND lease_token=$3 RETURNING id`,[task.id,task.revision,task.lease_token,task.check_interval_minutes,errorCode(error),meta.aiCalls,kind,task.next_check_at]);if(!updated.rowCount)return false;
  }
  await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,error_code,ai_called,ai_call_count,run_kind,tool_provenance,dependency_manifest) VALUES($1,$2,'failed',$3,$4,$5,$6,$7,$8)`,[task.id,task.revision,errorCode(error),meta.aiCalls>0,meta.aiCalls,kind,JSON.stringify([]),JSON.stringify([])]);await writeToolAudit(client,task,kind,'failed',meta,error);return true;
});}

async function finishUnchanged(task:ClaimedTask,source:SourceDocument,dependencies:MonitorDependency[],kind:'scheduled'|'manual'):Promise<boolean>{return transaction(async(client)=>{const owned=await client.query(`SELECT 1 FROM monitor_tasks WHERE id=$1 AND state='active' AND revision=$2 AND approved_revision=revision AND lease_token=$3 FOR UPDATE`,[task.id,task.revision,task.lease_token]);if(!owned.rowCount)return false;const authorization=await finalAuthorization(client,task);if(!authorization.owner||!authorization.actor){await rejectFinalAuthorization(client,task,kind,authorization.owner,{aiCalls:0,attemptedTools:0,provider:null,model:null,provenance:[],attempts:[],dependencies,fingerprint:source.fingerprint});return false;}const updated=await client.query(`UPDATE monitor_tasks SET check_count=check_count+1,unchanged_count=unchanged_count+1,last_checked_at=clock_timestamp(),next_check_at=CASE WHEN $9='scheduled' THEN clock_timestamp()+($4||' minutes')::interval ELSE $10 END,last_result='unchanged',error_code=NULL,source_final_url=$5,source_content_type=$6,source_etag=$7,source_last_modified=$8,lease_token=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE id=$1 AND revision=$2 AND lease_token=$3 RETURNING id`,[task.id,task.revision,task.lease_token,task.check_interval_minutes,source.finalUrl,source.contentType,source.etag??null,source.lastModified??null,kind,task.next_check_at]);if(!updated.rowCount)return false;await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,fingerprint,ai_called,ai_call_count,run_kind,source_url,dependency_manifest) VALUES($1,$2,'unchanged',$3,false,0,$4,$5,$6)`,[task.id,task.revision,source.fingerprint,kind,source.finalUrl,JSON.stringify(dependencies)]);return true;});}

function messageBody(event:{date:string;time:string|null;description:string;actions:string[]}):string{const when=`${event.date}${event.time?` ${event.time}`:''}`;const actions=event.actions.length?` · ${event.actions.join(' · ')}`:'';return `${event.description}${actions} · ${when}`.slice(0,1000);}

async function preview(task:ClaimedTask,source:SourceDocument,analysis:Analysis,meta:RunMeta,kind:'test'|'smarter'):Promise<boolean>{return transaction(async(client)=>{const updated=await client.query(`UPDATE monitor_tasks SET lease_token=NULL,lease_expires_at=NULL WHERE id=$1 AND revision=$2 AND lease_token=$3 RETURNING id`,[task.id,task.revision,task.lease_token]);const outcome=updated.rowCount?'changed':'superseded';await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,fingerprint,ai_called,ai_call_count,provider,model,run_kind,result_kind,result,source_url,tool_provenance,dependency_manifest) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,[task.id,task.revision,outcome,meta.fingerprint,meta.aiCalls>0,meta.aiCalls,meta.provider,meta.model,kind,analysis.kind,JSON.stringify(analysis.value),source.finalUrl,JSON.stringify(meta.provenance),JSON.stringify(meta.dependencies)]);await writeToolAudit(client,task,kind,'success',meta);return Boolean(updated.rowCount);});}

async function reconcileAnswer(task:ClaimedTask,source:SourceDocument,answer:ReturnType<typeof answerFromAi>,meta:RunMeta,kind:'scheduled'|'manual'):Promise<boolean>{return transaction(async(client)=>{const owned=await client.query(`SELECT 1 FROM monitor_tasks WHERE id=$1 AND state='active' AND revision=$2 AND approved_revision=revision AND lease_token=$3 FOR UPDATE`,[task.id,task.revision,task.lease_token]);if(!owned.rowCount){await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,fingerprint,ai_called,ai_call_count,provider,model,run_kind,result_kind,result,source_url,tool_provenance,dependency_manifest) VALUES($1,$2,'superseded',$3,$4,$5,$6,$7,$8,'answer',$9,$10,$11,$12)`,[task.id,task.revision,meta.fingerprint,meta.aiCalls>0,meta.aiCalls,meta.provider,meta.model,kind,JSON.stringify(answer),source.finalUrl,JSON.stringify(meta.provenance),JSON.stringify(meta.dependencies)]);await writeToolAudit(client,task,kind,'success',meta);return false;}const authorization=await finalAuthorization(client,task);if(!authorization.owner||!authorization.actor){await rejectFinalAuthorization(client,task,kind,authorization.owner,meta);return false;}await client.query(`UPDATE monitor_tasks SET check_count=check_count+1,ai_call_count=ai_call_count+$13,last_checked_at=clock_timestamp(),next_check_at=CASE WHEN $11='scheduled' THEN clock_timestamp()+($4||' minutes')::interval ELSE $12 END,last_result=$5,last_changed_at=clock_timestamp(),error_code=NULL,source_final_url=$6,source_content_type=$7,source_etag=$8,source_last_modified=$9,last_processed_fingerprint=$10,source_dependency_manifest=$14,lease_token=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE id=$1 AND revision=$2 AND lease_token=$3`,[task.id,task.revision,task.lease_token,task.check_interval_minutes,answer.answer,source.finalUrl,source.contentType,source.etag??null,source.lastModified??null,meta.fingerprint,kind,task.next_check_at,meta.aiCalls,JSON.stringify(meta.dependencies)]);await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,fingerprint,ai_called,ai_call_count,provider,model,run_kind,result_kind,result,source_url,tool_provenance,dependency_manifest) VALUES($1,$2,'changed',$3,$4,$5,$6,$7,$8,'answer',$9,$10,$11,$12)`,[task.id,task.revision,meta.fingerprint,meta.aiCalls>0,meta.aiCalls,meta.provider,meta.model,kind,JSON.stringify(answer),source.finalUrl,JSON.stringify(meta.provenance),JSON.stringify(meta.dependencies)]);await writeToolAudit(client,task,kind,'success',meta);return true;});}

async function reconcileEvents(task:ClaimedTask,source:SourceDocument,events:ReturnType<typeof extractionFromAi>['events'],meta:RunMeta,kind:'scheduled'|'manual'):Promise<boolean>{return transaction(async(client)=>{
  const owned=await client.query(`SELECT 1 FROM monitor_tasks WHERE id=$1 AND state='active' AND revision=$2 AND approved_revision=revision AND lease_token=$3 FOR UPDATE`,[task.id,task.revision,task.lease_token]);if(!owned.rowCount){await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,fingerprint,ai_called,ai_call_count,provider,model,run_kind,result_kind,result,source_url,tool_provenance,dependency_manifest) VALUES($1,$2,'superseded',$3,$4,$5,$6,$7,$8,'events',$9,$10,$11,$12)`,[task.id,task.revision,meta.fingerprint,meta.aiCalls>0,meta.aiCalls,meta.provider,meta.model,kind,JSON.stringify({version:1,events}),source.finalUrl,JSON.stringify(meta.provenance),JSON.stringify(meta.dependencies)]);await writeToolAudit(client,task,kind,'success',meta);return false;}const authorization=await finalAuthorization(client,task);if(!authorization.owner||!authorization.actor){await rejectFinalAuthorization(client,task,kind,authorization.owner,meta);return false;}
  const targets=await Promise.all([client.query<{person_id:string}>('SELECT person_id FROM monitor_task_person_targets WHERE task_id=$1',[task.id]),client.query<{display_id:string}>('SELECT display_id FROM monitor_task_display_targets WHERE task_id=$1',[task.id])]);const currentKeys=new Set<string>();
  for(const event of orderedMonitorEvents(events)){const key=monitorEventKey(task.id,event.eventKeyPart);currentKeys.add(key);const timing=(await client.query<{publish_at:Date;expires_at:Date}>(`SELECT ((($1::date-$2::int)+$3::time) AT TIME ZONE h.timezone) AS publish_at,(($1::date+1)::timestamp AT TIME ZONE h.timezone) AS expires_at FROM households h WHERE h.id=$4`,[event.date,task.notice_days_before,task.notice_local_time,task.household_id])).rows[0]!;const existing=(await client.query<{id:string;message_id:string|null}>(`SELECT id,message_id FROM monitor_events WHERE task_id=$1 AND event_key=$2 FOR UPDATE`,[task.id,key])).rows[0];let messageId=existing?.message_id??null;const body=messageBody(event);if(timing.expires_at>new Date()){if(messageId){const message=(await client.query<{state:string;revision:number}>('SELECT state,revision FROM messages WHERE id=$1 FOR UPDATE',[messageId])).rows[0];if(message&&['scheduled','published'].includes(message.state)){await client.query(`UPDATE messages SET body=$2,publish_at=CASE WHEN state='scheduled' THEN $3 ELSE publish_at END,expires_at=$4,revision=revision+1,updated_at=clock_timestamp() WHERE id=$1`,[messageId,body,timing.publish_at,timing.expires_at]);await client.query(`UPDATE message_display_targets SET delivery_state='queued',delivered_revision=NULL,delivered_at=NULL,displayed_at=NULL WHERE message_id=$1 AND delivery_state<>'cancelled'`,[messageId]);await client.query(`INSERT INTO message_lifecycle_events(message_id,from_state,to_state,revision,actor_type,idempotency_key) VALUES($1,$2,$2,$3,'worker',$4) ON CONFLICT DO NOTHING`,[messageId,message.state,message.revision+1,`monitor-update:${task.id}:${key}:${source.fingerprint}`]);}else messageId=null;}if(!messageId){const state=timing.publish_at>new Date()?'scheduled':'published';const inserted=await client.query<{id:string}>(`INSERT INTO messages(household_id,author_membership_id,body,importance,audience_household,publish_at,expires_at,state,idempotency_key,published_at) VALUES($1,$2,$3,'normal',false,$4,$5,$6,$7,CASE WHEN $6='published' THEN clock_timestamp() END) RETURNING id`,[task.household_id,task.owner_membership_id,body,timing.publish_at,timing.expires_at,state,`monitor:${task.id}:${key}:${source.fingerprint.slice(0,12)}`]);messageId=inserted.rows[0]!.id;for(const row of targets[0].rows)await client.query(`INSERT INTO message_person_audiences(household_id,message_id,person_id) VALUES($1,$2,$3)`,[task.household_id,messageId,row.person_id]);for(const row of targets[1].rows)await client.query(`INSERT INTO message_display_targets(household_id,message_id,display_id,delivery_state) VALUES($1,$2,$3,'queued')`,[task.household_id,messageId,row.display_id]);await client.query(`INSERT INTO message_lifecycle_events(message_id,to_state,revision,actor_type,idempotency_key) VALUES($1,$2,1,'worker',$3)`,[messageId,state,`monitor-create:${task.id}:${key}:${source.fingerprint.slice(0,12)}`]);}}
    const values=[task.household_id,task.id,key,event.date,event.time,event.type,event.description,JSON.stringify(event.actions),JSON.stringify(event.who),JSON.stringify(event.evidence),event.confidence,event.uncertainty,source.fingerprint,messageId];await client.query(`INSERT INTO monitor_events(household_id,task_id,event_key,event_date,event_time,event_type,description,actions,applies_to,evidence,confidence,uncertainty,source_fingerprint,message_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(task_id,event_key) DO UPDATE SET event_date=EXCLUDED.event_date,event_time=EXCLUDED.event_time,event_type=EXCLUDED.event_type,description=EXCLUDED.description,actions=EXCLUDED.actions,applies_to=EXCLUDED.applies_to,evidence=EXCLUDED.evidence,confidence=EXCLUDED.confidence,uncertainty=EXCLUDED.uncertainty,source_fingerprint=EXCLUDED.source_fingerprint,message_id=COALESCE(EXCLUDED.message_id,monitor_events.message_id),active=true,updated_at=clock_timestamp()`,values);}
  const removed=await client.query<{id:string;message_id:string|null}>(`UPDATE monitor_events SET active=false,updated_at=clock_timestamp() WHERE task_id=$1 AND active=true AND NOT(event_key=ANY($2::text[])) RETURNING id,message_id`,[task.id,[...currentKeys]]);for(const event of removed.rows){if(!event.message_id)continue;const message=(await client.query<{state:string;revision:number}>('SELECT state,revision FROM messages WHERE id=$1 FOR UPDATE',[event.message_id])).rows[0];if(message&&['scheduled','published'].includes(message.state)){const next=message.state==='scheduled'?'cancelled':'withdrawn';await client.query(`UPDATE messages SET state=$2,revision=revision+1,ended_at=clock_timestamp(),updated_at=clock_timestamp() WHERE id=$1`,[event.message_id,next]);await client.query(`UPDATE message_display_targets SET delivery_state='cancelled' WHERE message_id=$1`,[event.message_id]);await client.query(`INSERT INTO message_lifecycle_events(message_id,from_state,to_state,revision,actor_type,idempotency_key) VALUES($1,$2,$3,$4,'worker',$5)`,[event.message_id,message.state,next,message.revision+1,`monitor-remove:${task.id}:${event.id}:${source.fingerprint}`]);}}
  await client.query(`UPDATE monitor_tasks SET check_count=check_count+1,ai_call_count=ai_call_count+$13,last_checked_at=clock_timestamp(),next_check_at=CASE WHEN $11='scheduled' THEN clock_timestamp()+($4||' minutes')::interval ELSE $12 END,last_result=$5,last_changed_at=clock_timestamp(),error_code=NULL,source_final_url=$6,source_content_type=$7,source_etag=$8,source_last_modified=$9,last_processed_fingerprint=$10,source_dependency_manifest=$14,lease_token=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE id=$1 AND revision=$2 AND lease_token=$3`,[task.id,task.revision,task.lease_token,task.check_interval_minutes,`${events.length} event(s)`,source.finalUrl,source.contentType,source.etag??null,source.lastModified??null,meta.fingerprint,kind,task.next_check_at,meta.aiCalls,JSON.stringify(meta.dependencies)]);await client.query(`INSERT INTO monitor_runs(task_id,task_revision,outcome,fingerprint,ai_called,ai_call_count,provider,model,run_kind,result_kind,result,source_url,tool_provenance,dependency_manifest) VALUES($1,$2,'changed',$3,$4,$5,$6,$7,$8,'events',$9,$10,$11,$12)`,[task.id,task.revision,meta.fingerprint,meta.aiCalls>0,meta.aiCalls,meta.provider,meta.model,kind,JSON.stringify({version:1,events}),source.finalUrl,JSON.stringify(meta.provenance),JSON.stringify(meta.dependencies)]);await writeToolAudit(client,task,kind,'success',meta);return true;
});}

export class MonitorEngine{
  private readonly agent:MonitorAgentRunner;
  constructor(private readonly fetcher=new MonitorSourceFetcher(),private readonly ai=new AiAdminService()){this.agent=new MonitorAgentRunner(ai,fetcher);}
  private async execute(task:ClaimedTask,kind:MonitorRunKind):Promise<MonitorRunResult|'superseded'|'failed'>{
    const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),MONITOR_AGENT_DEADLINE_MS);
    let meta:RunMeta={aiCalls:0,attemptedTools:0,provider:null,model:null,provenance:[],attempts:[],dependencies:[],fingerprint:''};
    try{
      const approvedSourceUrl=normalizeMonitorUrl(task.source_url);
      const rule=task.interpreted_rule as {resultKind?:'events'|'answer'};const resultKind=rule.resultKind??'events';
      const production=kind==='scheduled'||kind==='manual';let seedDocuments:SourceDocument[]=[];
      if(production&&Array.isArray(task.source_dependency_manifest)&&task.source_dependency_manifest.length){
        const refreshed=await this.agent.refreshDependencies(task.source_dependency_manifest,controller.signal);seedDocuments=refreshed.documents;
        if(!refreshed.changed){const source=seedDocuments[0]!;const ok=await finishUnchanged(task,{...source,fingerprint:refreshed.fingerprint},task.source_dependency_manifest,kind);return ok?{outcome:'unchanged',resultKind:null,result:null,sourceUrl:source.finalUrl,checkedAt:new Date().toISOString(),sources:seedDocuments.map((item)=>({sourceUrl:item.finalUrl,fetchedAt:item.fetchedAt??new Date().toISOString()}))}:'superseded';}
      }else if(production&&task.last_processed_fingerprint){
        let fetched:SourceDocument;try{fetched=await this.fetcher.fetch(approvedSourceUrl,{followLinkedPdf:resultKind==='events',signal:controller.signal});}catch(error){if(error instanceof DomainError){const code=/^[A-Z][A-Z0-9_]{1,63}$/.test(error.code)?error.code:'MONITOR_SOURCE_UNAVAILABLE';throw new DomainError(error.code,error.status,{...(error.details??{}),attempts:[{tool:'web.open',requestedUrl:approvedSourceUrl,outcome:'failed',errorCode:code}]});}throw error;}const relevant=resultKind==='answer'?selectRelevantSource(fetched,{}):selectRelevantSource(fetched,rule);seedDocuments=[fetched];
        if(relevant.fingerprint===task.last_processed_fingerprint){const dependencies=[{url:fetched.finalUrl,fingerprint:fetched.fingerprint,contentType:fetched.contentType}];const ok=await finishUnchanged(task,relevant,dependencies,kind);return ok?{outcome:'unchanged',resultKind:null,result:null,sourceUrl:relevant.finalUrl,checkedAt:new Date().toISOString(),sources:[{sourceUrl:fetched.finalUrl,fetchedAt:fetched.fetchedAt??new Date().toISOString()}]}:'superseded';}
      }
      if(!(await stillOwned(task,production)))return'superseded';
      const tier:AiModelTier=kind==='smarter'?'strong':task.model_tier;
      const maxOutputTokens=resultKind==='answer'?300:4096;
      const schema=resultKind==='answer'?`{"version":1,"answer":string,"evidence":{"quote":"exact quote","sourceUrl":"exact fetched URL"},"confidence":0.0,"uncertainty":"string or null"}`:`{"version":1,"events":[{"date":"YYYY-MM-DD","time":"HH:MM or null","type":"string","description":"string","actions":["string"],"who":["string"],"evidence":{"quote":"exact quote","sourceUrl":"exact fetched URL"},"confidence":0.0,"uncertainty":"string or null"}]}`;
      const prompt=`Complete this approved Samvev task using current source evidence. The approved root URL is ${approvedSourceUrl}. You have the web.open tool and MUST use it before returning source facts. Open only the root and exact links returned by the tool; never construct or guess a link. Use fetched text and headings directly when they contain the answer. For a headline or title request, return the appropriate heading or link label from the current page without opening the article. For a top story or main article, prefer the first relevant editorial content link or linked headline; do not treat page titles, section labels or navigation labels as the story. Samvev performs network access; never say that you lack web access. After using tools, return only JSON matching ${schema}. Evidence quote must occur verbatim in the fetched document and evidence.sourceUrl must be an exact successfully opened URL, never merely a listed link URL. If the answer is a listed link label, cite the opened page URL that displayed it unless you opened the link. Answers and message-bearing event claims must be contiguous source passages. Never infer missing dates or facts. Rule: ${JSON.stringify(rule)}\nInstruction: ${task.instruction}`;
      const outcome:MonitorAgentResult=await this.agent.run({householdId:task.household_id,task:{operation:'extract',purpose:'monitor_source_analysis',input:prompt,modelTier:tier,maxOutputTokens,sources:[{url:approvedSourceUrl,observedAt:new Date().toISOString(),uncertainty:'unknown'}]},policy:task.provider_policy,rootUrl:approvedSourceUrl,seedDocuments,signal:controller.signal,requireTool:true});
      meta={aiCalls:outcome.aiCalls,attemptedTools:outcome.attemptedToolCount,provider:outcome.provider,model:outcome.model,provenance:outcome.provenance,attempts:outcome.attempts,dependencies:outcome.dependencies,fingerprint:monitorDependencyFingerprint(outcome.dependencies)};
      if(!outcome.documents.length)throw new DomainError('AI_RESPONSE_INVALID',502,{aiCalls:meta.aiCalls,attemptedToolCount:meta.attemptedTools,provenance:meta.provenance,attempts:meta.attempts,dependencies:meta.dependencies});
      const analysis:Analysis=resultKind==='answer'?{kind:'answer',value:answerFromAi(outcome.output,outcome.documents)}:{kind:'events',value:extractionFromAi(outcome.output,outcome.documents)};
      const evidenceUrl=analysis.kind==='answer'?analysis.value.evidence.sourceUrl:analysis.value.events[0]?.evidence.sourceUrl;
      const source=outcome.documents.find((item)=>item.finalUrl===evidenceUrl)??outcome.documents[0]!;
      const saved=kind==='test'||kind==='smarter'?await preview(task,source,analysis,meta,kind):analysis.kind==='answer'?await reconcileAnswer(task,source,analysis.value,meta,kind):await reconcileEvents(task,source,analysis.value.events,meta,kind);
      return saved?{outcome:'changed',resultKind:analysis.kind,result:analysis.value,sourceUrl:source.finalUrl,checkedAt:new Date().toISOString(),sources:publicSources(outcome.provenance)}:'superseded';
    }catch(error){const failure=failureMeta(error);if(failure.aiCalls||failure.attemptedTools||failure.provenance.length||failure.attempts.length)meta={...meta,aiCalls:failure.aiCalls,attemptedTools:failure.attemptedTools,provenance:failure.provenance,attempts:failure.attempts,dependencies:failure.dependencies,fingerprint:failure.fingerprint};return await finishFailure(task,error,meta,kind)?'failed':'superseded';}
    finally{clearTimeout(timeout);controller.abort();}
  }
  async runOnce():Promise<'idle'|'changed'|'unchanged'|'failed'|'superseded'>{const task=await claimOne();if(!task)return'idle';if(!task.owner_authorized)return await pauseUnauthorized(task)?'failed':'superseded';const result=await this.execute(task,'scheduled');return typeof result==='string'?result:result.outcome;}
  async runManual(actor:MonitorActor,id:string,expectedRevision:number,kind:'test'|'manual'|'smarter'):Promise<MonitorRunResult>{const task=await claimManual(actor,id,expectedRevision,kind);if(kind==='manual'&&!task.owner_authorized){await pauseUnauthorized(task);throw new DomainError('MONITOR_OWNER_UNAUTHORIZED',403);}const result=await this.execute(task,kind);await pool.query(`INSERT INTO audit_events(installation_id,household_id,actor_type,actor_id,action,subject_type,subject_id,metadata) VALUES($1,$2,'account',$3,$4,'monitor_task',$5,$6)`,[actor.installationId,actor.householdId,actor.accountId,`monitor.${kind}_run`,id,JSON.stringify({outcome:typeof result==='string'?result:result.outcome})]);if(result==='failed'){const last=(await pool.query<{error_code:string}>('SELECT error_code FROM monitor_runs WHERE task_id=$1 AND run_kind=$2 ORDER BY checked_at DESC LIMIT 1',[id,kind])).rows[0];const code=last?.error_code??'AI_UPSTREAM_ERROR';throw new DomainError(code as any,errorStatus(code));}if(result==='superseded')throw new DomainError('CONFLICT',409);return result;}
}
export async function runMonitorBatch(limit=5,engine=new MonitorEngine()):Promise<MonitorBatchResult>{const result={claimed:0,changed:0,unchanged:0,failed:0};for(let i=0;i<limit;i++){const outcome=await engine.runOnce();if(outcome==='idle')break;result.claimed++;if(outcome==='changed')result.changed++;else if(outcome==='unchanged')result.unchanged++;else if(outcome==='failed')result.failed++;}return result;}
