import { randomUUID } from 'node:crypto';
import {
  monitorAnswerSchema, monitorExtractionSchema, monitorInterpretationSchema,
  monitorTaskCreateSchema, monitorTaskUpdateSchema, type AiModelTier, type Capability, type MonitorProviderPolicy
} from '@samvev/contracts';
import { DomainError, requireCapability } from '@samvev/core';
import type pg from 'pg';
import { pool, transaction, type DbClient } from '../db.ts';
import { AiAdminService } from '../ai/admin-service.ts';
import { sourceUrlFromInstruction, type SourceDocument } from './source-fetcher.ts';

export interface MonitorActor { accountId:string; installationId:string; householdId:string; membershipId:string; capabilities:Capability[]; }
type Targets={personIds:string[];displayIds:string[]};

export function monitorJsonObject(text:string,invalidCode='MONITOR_INTERPRETATION_INVALID'):unknown {
  const trimmed=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');
  try{return JSON.parse(trimmed);}catch{throw new DomainError(invalidCode,502);}
}
export async function validateMonitorTargets(client:DbClient,actor:MonitorActor,targets:Targets):Promise<void>{
  if(!targets.personIds.length&&!targets.displayIds.length)throw new DomainError('VALIDATION_FAILED',400);
  requireCapability(actor.capabilities,'message.create.household');requireCapability(actor.capabilities,'message.schedule');
  const [people,displays]=await Promise.all([
    client.query('SELECT id FROM persons WHERE household_id=$1 AND id=ANY($2::uuid[])',[actor.householdId,targets.personIds]),
    client.query('SELECT id FROM displays WHERE household_id=$1 AND id=ANY($2::uuid[]) AND revoked_at IS NULL',[actor.householdId,targets.displayIds])
  ]);
  if(people.rowCount!==new Set(targets.personIds).size||displays.rowCount!==new Set(targets.displayIds).size)throw new DomainError('NOT_FOUND',404);
  if(targets.displayIds.length){requireCapability(actor.capabilities,'message.publish.display');if(!actor.capabilities.includes('display.manage')){const permitted=await client.query('SELECT display_id FROM membership_display_grants WHERE household_id=$1 AND membership_id=$2 AND display_id=ANY($3::uuid[])',[actor.householdId,actor.membershipId,targets.displayIds]);if(permitted.rowCount!==new Set(targets.displayIds).size)throw new DomainError('FORBIDDEN',403);}}
}
async function setTargets(client:DbClient,actor:MonitorActor,taskId:string,targets:Targets):Promise<void>{
  await validateMonitorTargets(client,actor,targets);
  await client.query('DELETE FROM monitor_task_person_targets WHERE task_id=$1',[taskId]);
  await client.query('DELETE FROM monitor_task_display_targets WHERE task_id=$1',[taskId]);
  for(const id of targets.personIds)await client.query('INSERT INTO monitor_task_person_targets(household_id,task_id,person_id) VALUES($1,$2,$3)',[actor.householdId,taskId,id]);
  for(const id of targets.displayIds)await client.query('INSERT INTO monitor_task_display_targets(household_id,task_id,display_id) VALUES($1,$2,$3)',[actor.householdId,taskId,id]);
}
export async function withdrawMonitorMessages(client:DbClient,taskId:string):Promise<void>{
  const rows=await client.query<{id:string;state:string;revision:number}>(`SELECT m.id,m.state,m.revision FROM monitor_events e JOIN messages m ON m.id=e.message_id WHERE e.task_id=$1 AND m.state IN ('scheduled','published') FOR UPDATE OF m`,[taskId]);
  for(const row of rows.rows){const next=row.state==='scheduled'?'cancelled':'withdrawn';await client.query(`UPDATE messages SET state=$2,revision=revision+1,ended_at=clock_timestamp(),updated_at=clock_timestamp() WHERE id=$1`,[row.id,next]);await client.query(`UPDATE message_display_targets SET delivery_state='cancelled' WHERE message_id=$1`,[row.id]);await client.query(`INSERT INTO message_lifecycle_events(message_id,from_state,to_state,revision,actor_type,idempotency_key) VALUES($1,$2,$3,$4,'system',$5) ON CONFLICT DO NOTHING`,[row.id,row.state,next,row.revision+1,`monitor-stop:${taskId}:${row.id}:${row.revision}`]);}
}

export const selectMonitorTask=`SELECT t.*,
 COALESCE((SELECT json_agg(person_id) FROM monitor_task_person_targets WHERE task_id=t.id),'[]') AS person_ids,
 COALESCE((SELECT json_agg(display_id) FROM monitor_task_display_targets WHERE task_id=t.id),'[]') AS display_ids,
 COALESCE((SELECT json_agg(json_build_object('date',event_date,'time',event_time,'type',event_type,'description',description,'actions',actions,'who',applies_to,'evidence',evidence,'confidence',confidence,'uncertainty',uncertainty) ORDER BY event_date,event_time) FROM monitor_events WHERE task_id=t.id AND active=true),'[]') AS events,
 (SELECT json_build_object('resultKind',r.result_kind,'result',r.result,'sourceUrl',r.source_url,'checkedAt',r.checked_at) FROM monitor_runs r WHERE t.last_changed_at IS NOT NULL AND r.task_id=t.id AND r.run_kind IN ('scheduled','manual') AND r.outcome='changed' AND r.result IS NOT NULL ORDER BY r.checked_at DESC,r.id DESC LIMIT 1) AS latest_result
 FROM monitor_tasks t`;
export function monitorTaskDto(row:Record<string,unknown>):Record<string,unknown>{
  const time=(row.notice_local_time as string|undefined)?.slice(0,5);
  return {id:row.id,name:row.name,instruction:row.instruction,sourceUrl:row.source_url,state:row.state,
    checkIntervalMinutes:row.check_interval_minutes,targets:{personIds:row.person_ids,displayIds:row.display_ids},noticeDaysBefore:row.notice_days_before,noticeLocalTime:time,
    providerPolicy:row.provider_policy,modelTier:row.model_tier,interpretedRule:row.interpreted_rule,revision:row.revision,approvedRevision:row.approved_revision,
    lastCheckedAt:(row.last_checked_at as Date|null)?.toISOString()??null,nextCheckAt:(row.next_check_at as Date|null)?.toISOString()??null,lastResult:row.last_result,
    lastChangedAt:(row.last_changed_at as Date|null)?.toISOString()??null,errorCode:row.error_code,
    source:{finalUrl:row.source_final_url,contentType:row.source_content_type,etag:row.source_etag,lastModified:row.source_last_modified,fingerprint:row.last_processed_fingerprint},
    latestResult:row.latest_result??null,events:row.events,stats:{checks:row.check_count,aiCalls:row.ai_call_count,unchanged:row.unchanged_count},createdAt:(row.created_at as Date).toISOString(),updatedAt:(row.updated_at as Date).toISOString()};
}
function derivedName(instruction:string,sourceUrl:string):string {const host=new URL(sourceUrl).hostname.replace(/^www\./,'');const first=instruction.split(/[.!?\n]/)[0]?.trim();return (first&&first.length<=80?first:`Følg med på ${host}`).slice(0,80);}

export class MonitorService{
  constructor(private readonly ai=new AiAdminService()){}
  async list(actor:MonitorActor){const rows=await pool.query(`${selectMonitorTask} WHERE t.household_id=$1 ORDER BY t.created_at DESC`,[actor.householdId]);return rows.rows.map((row)=>monitorTaskDto(row));}
  async create(actor:MonitorActor,input:unknown){const body=monitorTaskCreateSchema.parse(input);const sourceUrl=sourceUrlFromInstruction(body.instruction,body.sourceUrl);const name=body.name??derivedName(body.instruction,sourceUrl);return transaction(async(client)=>{await validateMonitorTargets(client,actor,body.targets);const inserted=await client.query<{id:string}>(`INSERT INTO monitor_tasks(household_id,owner_membership_id,name,instruction,source_url,check_interval_minutes,notice_days_before,notice_local_time,provider_policy,model_tier) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id`,[actor.householdId,actor.membershipId,name,body.instruction,sourceUrl,body.checkIntervalMinutes,body.noticeDaysBefore,body.noticeLocalTime,body.providerPolicy,body.modelTier]);const id=inserted.rows[0]!.id;await setTargets(client,actor,id,body.targets);await this.audit(client,actor,'monitor.created',id);return monitorTaskDto((await client.query(`${selectMonitorTask} WHERE t.id=$1`,[id])).rows[0]);});}
  async update(actor:MonitorActor,id:string,input:unknown){const body=monitorTaskUpdateSchema.parse(input);return transaction(async(client)=>{const current=(await client.query<Record<string,unknown>>(`${selectMonitorTask} WHERE t.id=$1 AND t.household_id=$2 FOR UPDATE OF t`,[id,actor.householdId])).rows[0];if(!current)throw new DomainError('NOT_FOUND',404);if(current.revision!==body.expectedRevision)throw new DomainError('REVISION_CONFLICT',409);const nextTargets=body.targets??{personIds:current.person_ids as string[],displayIds:current.display_ids as string[]};await validateMonitorTargets(client,actor,nextTargets);const nextInstruction=body.instruction??String(current.instruction);const nextUrl=sourceUrlFromInstruction(nextInstruction,body.sourceUrl??String(current.source_url));await withdrawMonitorMessages(client,id);await client.query(`UPDATE monitor_events SET active=false,updated_at=clock_timestamp() WHERE task_id=$1`,[id]);const updated=await client.query(`UPDATE monitor_tasks SET name=$3,instruction=$4,source_url=$5,check_interval_minutes=$6,notice_days_before=$7,notice_local_time=$8,provider_policy=$9,model_tier=$10,state='draft',interpreted_rule=NULL,approved_revision=NULL,last_checked_at=NULL,next_check_at=NULL,last_result=NULL,last_changed_at=NULL,error_code=NULL,source_final_url=NULL,source_content_type=NULL,source_etag=NULL,source_last_modified=NULL,last_processed_fingerprint=NULL,lease_token=NULL,lease_expires_at=NULL,revision=revision+1,updated_at=clock_timestamp() WHERE id=$1 AND household_id=$2 RETURNING id`,[id,actor.householdId,body.name??current.name,nextInstruction,nextUrl,body.checkIntervalMinutes??current.check_interval_minutes,body.noticeDaysBefore??current.notice_days_before,body.noticeLocalTime??String(current.notice_local_time).slice(0,5),body.providerPolicy??current.provider_policy,body.modelTier??current.model_tier]);if(!updated.rowCount)throw new DomainError('REVISION_CONFLICT',409);if(body.targets)await setTargets(client,actor,id,body.targets);await this.audit(client,actor,'monitor.updated',id);return monitorTaskDto((await client.query(`${selectMonitorTask} WHERE t.id=$1`,[id])).rows[0]);});}
  async interpret(actor:MonitorActor,id:string,expectedRevision:number){const token=randomUUID();const claimed=await pool.query(`UPDATE monitor_tasks SET lease_token=$4,lease_expires_at=clock_timestamp()+interval '2 minutes' WHERE id=$1 AND household_id=$2 AND revision=$3 AND state='draft' AND (lease_expires_at IS NULL OR lease_expires_at<clock_timestamp()) RETURNING id`,[id,actor.householdId,expectedRevision,token]);if(!claimed.rowCount){const current=(await pool.query<{revision:number;state:string}>('SELECT revision,state FROM monitor_tasks WHERE id=$1 AND household_id=$2',[id,actor.householdId])).rows[0];if(!current)throw new DomainError('NOT_FOUND',404);if(current.revision!==expectedRevision)throw new DomainError('REVISION_CONFLICT',409);throw new DomainError('CONFLICT',409);}try{const row=(await pool.query<Record<string,unknown>>(`${selectMonitorTask} WHERE t.id=$1 AND t.household_id=$2 AND t.lease_token=$3`,[id,actor.householdId,token])).rows[0];if(!row)throw new DomainError('CONFLICT',409);const prompt=`Return only JSON matching {"version":1,"resultKind":"events or answer","summary":string,"eventTypes":string[],"keywords":string[],"people":string[],"noticeDaysBefore":integer,"noticeLocalTime":"HH:MM","checkIntervalMinutes":integer}. Use resultKind "events" only for dated events/reminders and "answer" for a requested current fact, headline or summary. Interpret this monitor instruction without inventing facts. Instruction: ${JSON.stringify(row.instruction)}. Source: ${row.source_url}. Current defaults: notice ${row.notice_days_before} day(s) before at ${String(row.notice_local_time).slice(0,5)}, check every ${row.check_interval_minutes} minutes.`;const result=await this.ai.executeTask(actor.householdId,{operation:'plan',purpose:'monitor_interpretation',input:prompt,modelTier:row.model_tier as AiModelTier,maxOutputTokens:1200,sources:[]},row.provider_policy as MonitorProviderPolicy);const rule=monitorInterpretationSchema.safeParse(monitorJsonObject(result.output));if(!rule.success)throw new DomainError('MONITOR_INTERPRETATION_INVALID',502);const updated=await pool.query(`UPDATE monitor_tasks SET interpreted_rule=$3,notice_days_before=$4,notice_local_time=$5,check_interval_minutes=$6,revision=revision+1,approved_revision=NULL,state='draft',lease_token=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE id=$1 AND household_id=$2 AND revision=$7 AND lease_token=$8 RETURNING revision`,[id,actor.householdId,JSON.stringify(rule.data),rule.data.noticeDaysBefore,rule.data.noticeLocalTime,rule.data.checkIntervalMinutes,expectedRevision,token]);if(!updated.rowCount)throw new DomainError('REVISION_CONFLICT',409);return monitorTaskDto((await pool.query(`${selectMonitorTask} WHERE t.id=$1`,[id])).rows[0]);}catch(error){await pool.query('UPDATE monitor_tasks SET lease_token=NULL,lease_expires_at=NULL WHERE id=$1 AND household_id=$2 AND lease_token=$3',[id,actor.householdId,token]);throw error;}}
  async setState(actor:MonitorActor,id:string,expectedRevision:number,action:'approve'|'pause'|'resume'){return transaction(async(client)=>{const row=(await client.query<Record<string,unknown>>(`${selectMonitorTask} WHERE t.id=$1 AND t.household_id=$2 FOR UPDATE OF t`,[id,actor.householdId])).rows[0];if(!row)throw new DomainError('NOT_FOUND',404);if(row.revision!==expectedRevision)throw new DomainError('REVISION_CONFLICT',409);if((action==='approve'&&row.state!=='draft')||(action==='pause'&&row.state!=='active')||(action==='resume'&&row.state!=='paused'))throw new DomainError('CONFLICT',409);if(action==='approve'&&!row.interpreted_rule)throw new DomainError('MONITOR_INTERPRETATION_INVALID',422);if(action==='resume'&&!row.approved_revision)throw new DomainError('MONITOR_INTERPRETATION_INVALID',422);if(action==='approve')await validateMonitorTargets(client,actor,{personIds:row.person_ids as string[],displayIds:row.display_ids as string[]});const revision=expectedRevision+1;const state=action==='pause'?'paused':'active';if(action==='pause')await withdrawMonitorMessages(client,id);await client.query(`UPDATE monitor_tasks SET state=$3,owner_membership_id=CASE WHEN $5='approve' THEN $6 ELSE owner_membership_id END,revision=$4,approved_revision=CASE WHEN $5 IN ('approve','resume') THEN $4 ELSE approved_revision END,next_check_at=CASE WHEN $3='active' THEN clock_timestamp() ELSE NULL END,last_processed_fingerprint=CASE WHEN $5='pause' THEN NULL ELSE last_processed_fingerprint END,lease_token=NULL,lease_expires_at=NULL,updated_at=clock_timestamp() WHERE id=$1 AND household_id=$2`,[id,actor.householdId,state,revision,action,actor.membershipId]);await this.audit(client,actor,`monitor.${action}`,id);return monitorTaskDto((await client.query(`${selectMonitorTask} WHERE t.id=$1`,[id])).rows[0]);});}
  async setQuality(actor:MonitorActor,id:string,expectedRevision:number,quality:'standard'|'smarter'){return transaction(async(client)=>{const row=(await client.query<Record<string,unknown>>(`${selectMonitorTask} WHERE t.id=$1 AND t.household_id=$2 FOR UPDATE OF t`,[id,actor.householdId])).rows[0];if(!row)throw new DomainError('NOT_FOUND',404);if(row.revision!==expectedRevision)throw new DomainError('REVISION_CONFLICT',409);if(row.state==='draft')throw new DomainError('CONFLICT',409);await client.query(`UPDATE monitor_tasks SET model_tier=$3,revision=revision+1,approved_revision=CASE WHEN state='active' THEN revision+1 ELSE approved_revision END,updated_at=clock_timestamp() WHERE id=$1 AND household_id=$2`,[id,actor.householdId,quality==='smarter'?'strong':'routine']);await this.audit(client,actor,'monitor.quality_changed',id);return monitorTaskDto((await client.query(`${selectMonitorTask} WHERE t.id=$1`,[id])).rows[0]);});}
  async remove(actor:MonitorActor,id:string,expectedRevision:number){await transaction(async(client)=>{const row=await client.query<{revision:number}>('SELECT revision FROM monitor_tasks WHERE id=$1 AND household_id=$2 FOR UPDATE',[id,actor.householdId]);if(!row.rowCount)throw new DomainError('NOT_FOUND',404);if(row.rows[0]!.revision!==expectedRevision)throw new DomainError('REVISION_CONFLICT',409);await withdrawMonitorMessages(client,id);await this.audit(client,actor,'monitor.deleted',id);await client.query('DELETE FROM monitor_tasks WHERE id=$1',[id]);});}
  private async audit(client:pg.PoolClient,actor:MonitorActor,action:string,id:string){await client.query(`INSERT INTO audit_events(installation_id,household_id,actor_type,actor_id,action,subject_type,subject_id) VALUES($1,$2,'account',$3,$4,'monitor_task',$5)`,[actor.installationId,actor.householdId,actor.accountId,action,id]);}
}

function normalizedClaim(value:string):string{return value.normalize('NFKC').toLocaleLowerCase().replace(/\s+/g,' ').trim();}
function supportedByEvidence(value:string,evidence:string):boolean{return normalizedClaim(evidence).includes(normalizedClaim(value));}
export function extractionFromAi(output:string,source:SourceDocument,now=new Date()){const parsed=monitorExtractionSchema.safeParse(monitorJsonObject(output,'AI_RESPONSE_INVALID'));if(!parsed.success)throw new DomainError('AI_RESPONSE_INVALID',502);const text=normalizedClaim(source.text);const today=now.toISOString().slice(0,10);for(const event of parsed.data.events){const [year,month,day]=event.date.split('-');const dateForms=[event.date,`${day}.${month}.${year}`,`${day}/${month}/${year}`];const claims=[event.type,event.description,...event.actions,...event.who];if(event.date<today||event.evidence.sourceUrl!==source.finalUrl||!text.includes(normalizedClaim(event.evidence.quote))||!dateForms.some((value)=>text.includes(value))||claims.some((value)=>!supportedByEvidence(value,event.evidence.quote))||(event.time!==null&&!normalizedClaim(event.evidence.quote).includes(event.time)))throw new DomainError('AI_RESPONSE_INVALID',502);}return parsed.data;}
export function answerFromAi(output:string,source:SourceDocument){const parsed=monitorAnswerSchema.safeParse(monitorJsonObject(output,'AI_RESPONSE_INVALID'));if(!parsed.success)throw new DomainError('AI_RESPONSE_INVALID',502);const text=normalizedClaim(source.text);const quote=normalizedClaim(parsed.data.evidence.quote);const answer=normalizedClaim(parsed.data.answer);if(parsed.data.evidence.sourceUrl!==source.finalUrl||!text.includes(quote)||!text.includes(answer)||!supportedByEvidence(parsed.data.answer,parsed.data.evidence.quote))throw new DomainError('AI_RESPONSE_INVALID',502);return parsed.data;}
