#!/usr/bin/env node
import { createPublicKey,randomUUID,verify } from 'node:crypto';
import { createServer } from 'node:http';
import { promises as fs } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { spawn } from 'node:child_process';
// @ts-expect-error The companion core is deliberately plain ESM for standalone Node 24 use.
import { createOAuthAttempt,normalizeEarliestRefreshAt,normalizeHostId,selectIssuedClientId,validateOAuthCallback } from './chatgpt-connect-core.mjs';

const AUTHORIZE='https://auth.openai.com/api/accounts/authorize';
const TOKEN='https://auth.openai.com/api/accounts/oauth/token';
const RESOURCE='https://api.openai.com/v1';
const SCOPES='openid profile email offline_access resource.invoke chatgpt.tokens.use.direct';
function object(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function base64Json(value:string){const parsed=JSON.parse(Buffer.from(value,'base64url').toString('utf8'));if(!object(parsed))throw new Error('Invalid signed identity token');return parsed;}
async function validateOpenAiIdToken(idToken:string,clientId:string,expectedNonce:string){const parts=idToken.split('.');if(parts.length!==3)throw new Error('Invalid signed identity token');const header=base64Json(parts[0]!),payload=base64Json(parts[1]!);if(header.alg!=='RS256'||typeof header.kid!=='string')throw new Error('Unsupported signed identity token');const discoveryResponse=await fetch('https://auth.openai.com/.well-known/openid-configuration',{redirect:'error',signal:AbortSignal.timeout(10_000)});const discovery=await discoveryResponse.json() as unknown;if(!discoveryResponse.ok||!object(discovery)||discovery.issuer!=='https://auth.openai.com'||typeof discovery.jwks_uri!=='string'||!discovery.jwks_uri.startsWith('https://auth.openai.com/'))throw new Error('Invalid OpenAI discovery response');const jwksResponse=await fetch(discovery.jwks_uri,{redirect:'error',signal:AbortSignal.timeout(10_000)});const jwks=await jwksResponse.json() as unknown;const key=object(jwks)&&Array.isArray(jwks.keys)?jwks.keys.find((candidate)=>object(candidate)&&candidate.kid===header.kid&&candidate.kty==='RSA'):undefined;if(!object(key))throw new Error('Identity signing key was not found');let valid=false;try{valid=verify('RSA-SHA256',Buffer.from(`${parts[0]}.${parts[1]}`),createPublicKey({key:key as any,format:'jwk'}),Buffer.from(parts[2]!,'base64url'));}catch{}const audiences=typeof payload.aud==='string'?[payload.aud]:Array.isArray(payload.aud)?payload.aud:[];const now=Math.floor(Date.now()/1000);const timesValid=typeof payload.exp==='number'&&payload.exp>now&&(payload.nbf===undefined||(typeof payload.nbf==='number'&&payload.nbf<=now+60&&payload.nbf<=payload.exp))&&(payload.iat===undefined||(typeof payload.iat==='number'&&payload.iat<=now+300&&payload.iat<=payload.exp));if(!valid||payload.iss!=='https://auth.openai.com'||!audiences.includes(clientId)||typeof payload.sub!=='string'||!timesValid||payload.nonce!==expectedNonce)throw new Error('Signed identity validation failed');return{issuer:'https://auth.openai.com',subject:payload.sub,email:typeof payload.email==='string'?payload.email:undefined};}
function argument(name:string){const i=process.argv.indexOf(name);return i>=0?process.argv[i+1]:undefined;}
const output=resolve(argument('--output')??'.local/chatgpt/samvev-chatgpt-credential.json');
const reauthorize=argument('--reauthorize');
const suppliedHostId=argument('--host-id');
const hostFile=resolve(argument('--host-file')??`${dirname(output)}/samvev-host-id`);

async function protectedRead(path:string){const stat=await fs.stat(path);if((stat.mode&0o077)!==0)throw new Error(`Refusing credential file with permissions other than 0600: ${path}`);return fs.readFile(path,'utf8');}
async function atomic0600(path:string,value:string){await fs.mkdir(dirname(path),{recursive:true,mode:0o700});const temporary=`${path}.${process.pid}.tmp`;await fs.writeFile(temporary,value,{mode:0o600,flag:'wx'});await fs.rename(temporary,path);await fs.chmod(path,0o600);}
async function hostId(){if(suppliedHostId)return normalizeHostId(suppliedHostId);try{return normalizeHostId((await protectedRead(hostFile)).trim());}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;const value=`urn:uuid:${randomUUID()}`;await atomic0600(hostFile,`${value}\n`);return value;}}
async function main(){
  const previous=reauthorize?JSON.parse(await protectedRead(resolve(reauthorize))):undefined;
  const stableHostId=await hostId();
  const {state,nonce,verifier,challenge}=createOAuthAttempt();
  const callback=await new Promise<{url:URL;redirectUri:string}>((resolveCallback,reject)=>{
    let redirectUri='',settled=false;const finish=(error?:unknown,result?:{url:URL;redirectUri:string})=>{if(settled)return;settled=true;clearTimeout(timer);server.close();if(error)reject(error);else resolveCallback(result!);};const timer=setTimeout(()=>finish(new Error('Authorization timed out')),300_000);
    const server=createServer((request,response)=>{try{const url=new URL(request.url??'/',`http://${request.headers.host}`);if(url.pathname!=='/auth/callback'){response.writeHead(404).end();return;}validateOAuthCallback(url,state);response.writeHead(200,{'content-type':'text/plain; charset=utf-8'}).end('Samvev authorization received. You can close this window.');finish(undefined,{url,redirectUri});}catch(error){response.writeHead(400,{'content-type':'text/plain; charset=utf-8'}).end('Samvev rejected this authorization callback.');finish(error);}});
    server.on('error',(error)=>finish(error));server.listen(0,'127.0.0.1',()=>{
      const port=(server.address() as {port:number}).port;redirectUri=`http://127.0.0.1:${port}/auth/callback`;const clientId=previous?.clientId??'dynamic_agent_client';const parameters=new URLSearchParams({client_id:clientId,ext_agent_host_id:'pending',response_type:'code',redirect_uri:redirectUri,scope:SCOPES,resource:RESOURCE,state,nonce,code_challenge_method:'S256',code_challenge:challenge});
      Promise.resolve(stableHostId).then((id)=>{parameters.set('ext_agent_host_id',id);if(!previous)parameters.set('agent_name_hint','Samvev');else{if(previous.idToken)parameters.set('id_token_hint',previous.idToken);if(previous.email)parameters.set('login_hint',previous.email);}const url=`${AUTHORIZE}?${parameters}`;
        if(previous){const command=process.platform==='darwin'?'open':process.platform==='win32'?'cmd':'xdg-open';const args=process.platform==='win32'?['/c','start','',url]:[url];const child=spawn(command,args,{stdio:'ignore',detached:true});child.once('error',(error)=>finish(error));child.once('exit',(code)=>{if(code!==0)finish(new Error('Could not open the system browser'));});child.unref();console.log('Opened the OpenAI authorization page in the system browser.');}
        else console.log(`Open this local authorization URL in your browser:\n${url}`);
      }).catch((error)=>finish(error));
    });
  });
  const validated=validateOAuthCallback(callback.url,state);if('error' in validated)throw new Error(`Authorization declined: ${validated.error}`);const code=validated.code;const suppliedClient=callback.url.searchParams.get('client_id');const clientId=selectIssuedClientId(previous?.clientId,suppliedClient);
  const response=await fetch(TOKEN,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:clientId,code,code_verifier:verifier,redirect_uri:callback.redirectUri,resource:RESOURCE}),redirect:'error',signal:AbortSignal.timeout(10_000)});const tokenText=await response.text();if(Buffer.byteLength(tokenText)>512*1024)throw new Error('OpenAI token response was too large');let token:Record<string,unknown>;try{token=JSON.parse(tokenText);}catch{throw new Error('OpenAI token exchange failed');}if(!response.ok||typeof token.id_token!=='string'||typeof token.access_token!=='string'||typeof token.refresh_token!=='string'||typeof token.expires_in!=='number')throw new Error('OpenAI token exchange failed');
  const identity=await validateOpenAiIdToken(token.id_token,clientId,nonce);if(previous&&(identity.issuer!==previous.issuer||identity.subject!==previous.subject))throw new Error('Reauthorization returned a different ChatGPT identity');const scopes=(typeof token.scope==='string'?token.scope:'').split(/\s+/).filter(Boolean);if(!['openid','profile','email','offline_access','resource.invoke','chatgpt.tokens.use.direct'].every((scope)=>scopes.includes(scope)))throw new Error('ChatGPT plan permission was not granted');
  const savedAt=new Date();const earliestRefreshAt=normalizeEarliestRefreshAt(token.earliest_refresh_at);const record={version:1,label:identity.email??`ChatGPT ${identity.subject.slice(-6)}`,...(identity.email?{email:identity.email}:{}),issuer:identity.issuer,subject:identity.subject,clientId,extAgentHostId:stableHostId,idToken:token.id_token,accessToken:token.access_token,refreshToken:token.refresh_token,tokenType:'Bearer',expiresAt:new Date(savedAt.getTime()+token.expires_in*1000).toISOString(),...(earliestRefreshAt?{earliestRefreshAt}:{}),scopes,savedAt:savedAt.toISOString()};await atomic0600(output,`${JSON.stringify(record,null,2)}\n`);console.log(`Credential record saved with 0600 permissions: ${output}`);console.log('Transfer it with SSH/SCP, import it on the Samvev VM, then delete the transfer copy.');
}
if(process.argv[1]?.endsWith('chatgpt-connect.ts'))main().catch((error)=>{console.error(error instanceof Error?error.message:'ChatGPT connection failed');process.exitCode=1;});
