import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import { resolve } from 'node:path';
import test, { after, before } from 'node:test';
import type { FastifyInstance } from 'fastify';
import { roleCapabilityPresets } from '@samvev/contracts';
import { tokenHash } from '@samvev/core';
import { buildApp } from './app.ts';
import { pool } from './db.ts';
import { migrate } from './db/migrate.ts';
import { AiAdminService } from './ai/admin-service.ts';
import { MonitorEngine } from './monitor/engine.ts';
import type { MonitorSourceFetcher, SourceDocument } from './monitor/source-fetcher.ts';

const guard=new URL(process.env.DATABASE_URL??'');assert.equal(guard.hostname,'test-db');assert.equal(guard.pathname,'/samvev_test');
const keyDir=resolve(process.cwd(),'.local/m23-api-test');const keyFile=resolve(keyDir,'master-key');
let app:FastifyInstance;let ai:AiAdminService;let aiCalls=0;let extractionEvents:any[]=[];let failProvider=false;let beforeProviderResponse:(()=>Promise<void>)|undefined;
const transport=async(_url:string,init:RequestInit)=>{aiCalls++;if(failProvider)throw new Error('synthetic failure');const body=JSON.parse(String(init.body));const input=String(body.input??body.messages?.[0]?.content??'');const headline=input.includes('present the headline');const output=input.includes('monitor instruction')?JSON.stringify({version:1,resultKind:headline?'answer':'events',summary:headline?'Read the current headline from the approved source.':'Find future trip days and notify the selected display the evening before.',eventTypes:headline?[]:['trip day'],keywords:headline?[]:['trip'],people:headline?[]:['A'],noticeDaysBefore:1,noticeLocalTime:'18:00',checkIntervalMinutes:60}):headline?JSON.stringify({version:1,answer:'Synthetic headline',evidence:{quote:'Synthetic headline',sourceUrl:source.finalUrl},confidence:0.99,uncertainty:null}):JSON.stringify({version:1,events:extractionEvents});if(beforeProviderResponse){const callback=beforeProviderResponse;beforeProviderResponse=undefined;await callback();}if(body.messages)return new Response(JSON.stringify({choices:[{message:{content:output}}],usage:{prompt_tokens:12,completion_tokens:8}}),{status:200});return new Response(JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:output}]}],usage:{input_tokens:12,output_tokens:8}}),{status:200});};
let source:SourceDocument={finalUrl:'https://example.com/plan',contentType:'text/html',text:'Trip day 2030-09-20 for A. Bring a backpack.',fingerprint:'fingerprint-one'};
const fetcher={fetch:async()=>source} as unknown as MonitorSourceFetcher;
function auth(token:string,csrf:string){return {cookie:`samvev_session=${token}`,'x-csrf-token':csrf};}

before(async()=>{await migrate();await fs.rm(keyDir,{recursive:true,force:true});ai=new AiAdminService({keyFile,transport});app=await buildApp({aiKeyFile:keyFile,aiTransport:transport,monitorFetcher:fetcher});});
after(async()=>{await app.close();await pool.end();await fs.rm(keyDir,{recursive:true,force:true});});

test('admin-approved monitor uses change detection and reconciles durable M1 messages',async()=>{
  await pool.query('TRUNCATE installations,pairing_requests,rate_limits RESTART IDENTITY CASCADE');
  const installationId=(await pool.query<{id:string}>(`INSERT INTO installations(claimed_at,claim_token_hash,setup_step) VALUES(clock_timestamp(),NULL,'complete') RETURNING id`)).rows[0]!.id;
  const householdId=(await pool.query<{id:string}>(`INSERT INTO households(installation_id,name,timezone,default_locale) VALUES($1,'Synthetic monitor household','Europe/Oslo','en') RETURNING id`,[installationId])).rows[0]!.id;
  const otherHouseholdId=(await pool.query<{id:string}>(`INSERT INTO households(installation_id,name,timezone,default_locale) VALUES($1,'Other synthetic household','Europe/Oslo','en') RETURNING id`,[installationId])).rows[0]!.id;
  const makeAccount=async(name:string,email:string,capabilities:readonly string[])=>{const personId=(await pool.query<{id:string}>('INSERT INTO persons(household_id,display_name,age_group) VALUES($1,$2,\'adult\') RETURNING id',[householdId,name])).rows[0]!.id;const accountId=(await pool.query<{id:string}>(`INSERT INTO accounts(installation_id,email_normalized,password_hash,locale,theme) VALUES($1,$2,'unused','en','system') RETURNING id`,[installationId,email])).rows[0]!.id;const membershipId=(await pool.query<{id:string}>(`INSERT INTO memberships(household_id,account_id,person_id,role_preset,capabilities) VALUES($1,$2,$3,'limited',$4) RETURNING id`,[householdId,accountId,personId,JSON.stringify(capabilities)])).rows[0]!.id;const token=`${name}-synthetic-session-token`;const csrf=`${name}-synthetic-csrf-token`;await pool.query(`INSERT INTO sessions(account_id,token_hash,csrf_hash,expires_at) VALUES($1,$2,$3,clock_timestamp()+interval '1 hour')`,[accountId,tokenHash(token),tokenHash(csrf)]);return{accountId,personId,membershipId,token,csrf};};
  const admin=await makeAccount('admin','monitor-admin@test.invalid',roleCapabilityPresets.household_admin);const member=await makeAccount('member','monitor-member@test.invalid',['household.view']);const narrowed=await makeAccount('narrowed','monitor-narrowed@test.invalid',['household.manage','message.create.household','message.schedule','message.publish.display']);
  const displayId=(await pool.query<{id:string}>(`INSERT INTO displays(household_id,name,locale,theme,privacy_mode,allowed_content) VALUES($1,'Kitchen','en','system',false,'household_messages') RETURNING id`,[householdId])).rows[0]!.id;
  await ai.updateSettings(householdId,{enabled:true,provider:'openai',apiKey:'synthetic-openai-key-for-monitor-tests',defaultModel:'synthetic-routine',strongModel:'synthetic-strong',expectedRevision:0});
  const base=`/api/v1/households/${householdId}/monitors`;
  const narrowPayload={name:'Granted target test',instruction:'Find future trip days at example.com for the selected display.',sourceUrl:'https://example.com/plan',checkIntervalMinutes:60,noticeDaysBefore:1,noticeLocalTime:'18:00',targets:{personIds:[narrowed.personId],displayIds:[displayId]}};
  assert.equal((await app.inject({method:'POST',url:base,headers:auth(narrowed.token,narrowed.csrf),payload:narrowPayload})).statusCode,403);
  await pool.query('INSERT INTO membership_display_grants(household_id,membership_id,display_id) VALUES($1,$2,$3)',[householdId,narrowed.membershipId,displayId]);
  const granted=await app.inject({method:'POST',url:base,headers:auth(narrowed.token,narrowed.csrf),payload:narrowPayload});assert.equal(granted.statusCode,201,granted.body);
  const grantedRule=await app.inject({method:'POST',url:`${base}/${granted.json().id}/interpret`,headers:auth(narrowed.token,narrowed.csrf),payload:{expectedRevision:granted.json().revision}});assert.equal(grantedRule.statusCode,200,grantedRule.body);
  await pool.query('DELETE FROM membership_display_grants WHERE membership_id=$1',[narrowed.membershipId]);assert.equal((await app.inject({method:'POST',url:`${base}/${granted.json().id}/approve`,headers:auth(narrowed.token,narrowed.csrf),payload:{expectedRevision:grantedRule.json().revision}})).statusCode,403);
  await pool.query('INSERT INTO membership_display_grants(household_id,membership_id,display_id) VALUES($1,$2,$3)',[householdId,narrowed.membershipId,displayId]);const grantedApproved=await app.inject({method:'POST',url:`${base}/${granted.json().id}/approve`,headers:auth(narrowed.token,narrowed.csrf),payload:{expectedRevision:grantedRule.json().revision}});assert.equal(grantedApproved.statusCode,200,grantedApproved.body);const callsBeforeGrantRevocation=aiCalls;beforeProviderResponse=async()=>{await pool.query('DELETE FROM membership_display_grants WHERE membership_id=$1',[narrowed.membershipId]);};const ownerGrantRace=await app.inject({method:'POST',url:`${base}/${granted.json().id}/run`,headers:auth(narrowed.token,narrowed.csrf),payload:{expectedRevision:grantedApproved.json().revision}});assert.equal(ownerGrantRace.statusCode,409,ownerGrantRace.body);assert.equal(aiCalls,callsBeforeGrantRevocation+1);const grantPaused=(await pool.query<{state:string;revision:number}>('SELECT state,revision FROM monitor_tasks WHERE id=$1',[granted.json().id])).rows[0]!;assert.equal(grantPaused.state,'paused');assert.equal((await pool.query('SELECT count(*)::int AS n FROM messages WHERE author_membership_id=$1',[narrowed.membershipId])).rows[0].n,0);assert.equal((await app.inject({method:'DELETE',url:`${base}/${granted.json().id}`,headers:auth(narrowed.token,narrowed.csrf),payload:{expectedRevision:grantPaused.revision}})).statusCode,200);await pool.query('INSERT INTO membership_display_grants(household_id,membership_id,display_id) VALUES($1,$2,$3)',[householdId,narrowed.membershipId,displayId]);
  assert.equal((await app.inject({method:'GET',url:base})).statusCode,401);assert.equal((await app.inject({method:'GET',url:base,headers:{cookie:`samvev_session=${member.token}`}})).statusCode,403);
  assert.equal((await app.inject({method:'GET',url:`/api/v1/households/${otherHouseholdId}/monitors`,headers:{cookie:`samvev_session=${admin.token}`}})).statusCode,404);
  const createPayload={name:'Trip reminders',instruction:'Find future trip days for A and notify the kitchen display the evening before.',sourceUrl:'https://example.com/plan',checkIntervalMinutes:60,noticeDaysBefore:1,noticeLocalTime:'18:00',targets:{personIds:[admin.personId],displayIds:[displayId]},providerPolicy:'openai',modelTier:'routine'};
  assert.equal((await app.inject({method:'POST',url:base,headers:{cookie:`samvev_session=${admin.token}`},payload:createPayload})).statusCode,403);
  assert.equal((await app.inject({method:'POST',url:base,headers:{...auth(admin.token,admin.csrf),origin:'https://attacker.invalid'},payload:createPayload})).statusCode,403);
  const created=await app.inject({method:'POST',url:base,headers:auth(admin.token,admin.csrf),payload:{name:'Trip reminders',instruction:'Find future trip days for A and notify the kitchen display the evening before.',sourceUrl:'https://example.com/plan',checkIntervalMinutes:60,noticeDaysBefore:1,noticeLocalTime:'18:00',targets:{personIds:[admin.personId],displayIds:[displayId]},providerPolicy:'openai',modelTier:'routine'}});
  assert.equal(created.statusCode,201,created.body);assert.equal(created.json().state,'draft');assert.equal(created.json().interpretedRule,null);
  const interpreted=await app.inject({method:'POST',url:`${base}/${created.json().id}/interpret`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:1}});assert.equal(interpreted.statusCode,200,interpreted.body);assert.match(interpreted.json().interpretedRule.summary,/trip days/);
  const approved=await app.inject({method:'POST',url:`${base}/${created.json().id}/approve`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:2}});assert.equal(approved.statusCode,200,approved.body);assert.equal(approved.json().state,'active');
  const interpretationCalls=aiCalls;extractionEvents=[{date:'2030-09-20',time:null,type:'trip day',description:'Trip day 2030-09-20 for A',actions:['Bring a backpack'],who:['A'],evidence:{quote:'Trip day 2030-09-20 for A',sourceUrl:source.finalUrl},confidence:0.96,uncertainty:null}];
  extractionEvents[0].evidence.quote=source.text;const engine=new MonitorEngine(fetcher,ai);assert.equal(await engine.runOnce(),'changed');assert.equal(aiCalls,interpretationCalls+1);
  const message=(await pool.query<{id:string;state:string;body:string}>('SELECT id,state,body FROM messages')).rows[0]!;assert.equal(message.state,'scheduled');assert.match(message.body,/Bring a backpack/);assert.equal((await pool.query('SELECT 1 FROM message_display_targets WHERE message_id=$1 AND display_id=$2',[message.id,displayId])).rowCount,1);
  await pool.query(`UPDATE monitor_tasks SET next_check_at=clock_timestamp() WHERE id=$1`,[created.json().id]);assert.equal(await new MonitorEngine(fetcher,ai).runOnce(),'unchanged');assert.equal(aiCalls,interpretationCalls+1);assert.equal((await pool.query('SELECT count(*)::int AS n FROM messages')).rows[0].n,1);
  source={...source,text:'Updated trip day 2030-09-20 for A. Bring boots.',fingerprint:'fingerprint-two'};extractionEvents=[{...extractionEvents[0],description:'Updated trip day 2030-09-20 for A',actions:['Bring boots'],evidence:{quote:source.text,sourceUrl:source.finalUrl}}];await pool.query(`UPDATE monitor_tasks SET next_check_at=clock_timestamp(),lease_token=gen_random_uuid(),lease_expires_at=clock_timestamp()-interval '1 second' WHERE id=$1`,[created.json().id]);assert.equal(await new MonitorEngine(fetcher,ai).runOnce(),'changed');assert.equal((await pool.query('SELECT count(*)::int AS n FROM messages')).rows[0].n,1);assert.match((await pool.query<{body:string}>('SELECT body FROM messages WHERE id=$1',[message.id])).rows[0]!.body,/Updated trip day.*Bring boots/);
  source={...source,text:'No future trips listed',fingerprint:'fingerprint-three'};extractionEvents=[];await pool.query(`UPDATE monitor_tasks SET next_check_at=clock_timestamp() WHERE id=$1`,[created.json().id]);assert.equal(await engine.runOnce(),'changed');assert.equal((await pool.query<{state:string}>('SELECT state FROM messages WHERE id=$1',[message.id])).rows[0]!.state,'cancelled');
  const successfulFingerprint=(await pool.query<{last_processed_fingerprint:string}>('SELECT last_processed_fingerprint FROM monitor_tasks WHERE id=$1',[created.json().id])).rows[0]!.last_processed_fingerprint;source={...source,text:'Provider failure version',fingerprint:'fingerprint-four'};failProvider=true;await pool.query(`UPDATE monitor_tasks SET next_check_at=clock_timestamp() WHERE id=$1`,[created.json().id]);assert.equal(await engine.runOnce(),'failed');const failed=(await pool.query<{error_code:string;last_processed_fingerprint:string}>('SELECT error_code,last_processed_fingerprint FROM monitor_tasks WHERE id=$1',[created.json().id])).rows[0]!;assert.equal(failed.error_code,'AI_UPSTREAM_ERROR');assert.equal(failed.last_processed_fingerprint,successfulFingerprint);failProvider=false;
  await assert.rejects(()=>ai.executeTask(householdId,{operation:'extract',purpose:'policy_test',input:'synthetic',modelTier:'routine',sources:[]},'local'),(error:any)=>error.code==='AI_PROVIDER_UNAVAILABLE');
  const listed=(await app.inject({method:'GET',url:base,headers:{cookie:`samvev_session=${admin.token}`}})).json().tasks[0];assert.equal(listed.stats.checks,5);assert.equal(listed.stats.aiCalls,4);assert.equal(listed.stats.unchanged,1);
  await pool.query(`UPDATE messages SET state='scheduled',publish_at=clock_timestamp()+interval '1 day',expires_at=clock_timestamp()+interval '2 days',ended_at=NULL WHERE id=$1`,[message.id]);await pool.query(`UPDATE message_display_targets SET delivery_state='queued' WHERE message_id=$1`,[message.id]);
  const paused=await app.inject({method:'POST',url:`${base}/${created.json().id}/pause`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:listed.revision}});assert.equal(paused.json().state,'paused');assert.equal((await pool.query('SELECT state FROM messages WHERE id=$1',[message.id])).rows[0].state,'cancelled');assert.equal((await pool.query('SELECT delivery_state FROM message_display_targets WHERE message_id=$1',[message.id])).rows[0].delivery_state,'cancelled');
  const resumed=await app.inject({method:'POST',url:`${base}/${created.json().id}/resume`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:paused.json().revision}});assert.equal(resumed.statusCode,200,resumed.body);assert.equal(resumed.json().state,'active');
  const callsBeforeRevocation=aiCalls;await pool.query('UPDATE accounts SET disabled_at=clock_timestamp() WHERE id=$1',[admin.accountId]);assert.equal(await engine.runOnce(),'failed');assert.equal(aiCalls,callsBeforeRevocation);const authorizationPause=(await pool.query<{state:string;revision:number;error_code:string}>('SELECT state,revision,error_code FROM monitor_tasks WHERE id=$1',[created.json().id])).rows[0]!;assert.equal(authorizationPause.state,'paused');assert.equal(authorizationPause.error_code,'MONITOR_OWNER_UNAUTHORIZED');await pool.query('UPDATE accounts SET disabled_at=NULL WHERE id=$1',[admin.accountId]);
  const resumedAfterAuth=await app.inject({method:'POST',url:`${base}/${created.json().id}/resume`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:authorizationPause.revision}});assert.equal(resumedAfterAuth.statusCode,200,resumedAfterAuth.body);
  const edited=await app.inject({method:'PATCH',url:`${base}/${created.json().id}`,headers:auth(admin.token,admin.csrf),payload:{name:'Updated trip reminders',expectedRevision:resumedAfterAuth.json().revision}});assert.equal(edited.json().state,'draft');assert.equal(edited.json().approvedRevision,null);
  assert.equal((await pool.query('SELECT last_processed_fingerprint FROM monitor_tasks WHERE id=$1',[created.json().id])).rows[0].last_processed_fingerprint,null);
  const removed=await app.inject({method:'DELETE',url:`${base}/${created.json().id}`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:edited.json().revision}});assert.equal(removed.statusCode,200);assert.equal((await pool.query('SELECT 1 FROM monitor_tasks WHERE id=$1',[created.json().id])).rowCount,0);

  source={finalUrl:'https://example.com/',contentType:'text/html',text:'Synthetic headline\nSupporting detail',fingerprint:'headline-one'};
  const natural=await app.inject({method:'POST',url:base,headers:auth(admin.token,admin.csrf),payload:{instruction:'Check example.com and present the headline',checkIntervalMinutes:60,noticeDaysBefore:1,noticeLocalTime:'18:00',targets:{personIds:[admin.personId],displayIds:[displayId]}}});
  assert.equal(natural.statusCode,201,natural.body);assert.equal(natural.json().sourceUrl,'https://example.com/');
  const callsBeforeConcurrentInterpret=aiCalls;const interpretations=await Promise.all([app.inject({method:'POST',url:`${base}/${natural.json().id}/interpret`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:natural.json().revision}}),app.inject({method:'POST',url:`${base}/${natural.json().id}/interpret`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:natural.json().revision}})]);assert.deepEqual(interpretations.map((response)=>response.statusCode).sort(),[200,409]);assert.equal(aiCalls,callsBeforeConcurrentInterpret+1);const answerRule=interpretations.find((response)=>response.statusCode===200)!;assert.equal(answerRule.json().interpretedRule.resultKind,'answer');
  for(const action of ['test','run','smarter','quality']){const payload=action==='quality'?{expectedRevision:answerRule.json().revision,quality:'smarter'}:{expectedRevision:answerRule.json().revision};assert.equal((await app.inject({method:'POST',url:`${base}/${natural.json().id}/${action}`,headers:auth(member.token,member.csrf),payload})).statusCode,403,action);assert.equal((await app.inject({method:'POST',url:`/api/v1/households/${otherHouseholdId}/monitors/${natural.json().id}/${action}`,headers:auth(admin.token,admin.csrf),payload})).statusCode,404,action);}
  const beforeTest=(await pool.query<{next_check_at:Date|null;check_count:number;ai_call_count:number}>('SELECT next_check_at,check_count,ai_call_count FROM monitor_tasks WHERE id=$1',[natural.json().id])).rows[0]!;
  const tested=await app.inject({method:'POST',url:`${base}/${natural.json().id}/test`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:answerRule.json().revision}});assert.equal(tested.statusCode,200,tested.body);assert.equal(tested.json().result.answer,'Synthetic headline');
  const afterTest=(await pool.query<{state:string;revision:number;next_check_at:Date|null;check_count:number;ai_call_count:number;last_processed_fingerprint:string|null}>('SELECT state,revision,next_check_at,check_count,ai_call_count,last_processed_fingerprint FROM monitor_tasks WHERE id=$1',[natural.json().id])).rows[0]!;assert.equal(afterTest.state,'draft');assert.equal(afterTest.revision,answerRule.json().revision);assert.equal(afterTest.next_check_at,beforeTest.next_check_at);assert.equal(afterTest.check_count,beforeTest.check_count);assert.equal(afterTest.ai_call_count,beforeTest.ai_call_count);assert.equal(afterTest.last_processed_fingerprint,null);assert.equal((await pool.query(`SELECT count(*)::int AS n FROM monitor_runs WHERE task_id=$1 AND run_kind='test'`,[natural.json().id])).rows[0].n,1);
  const activated=await app.inject({method:'POST',url:`${base}/${natural.json().id}/approve`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:afterTest.revision}});assert.equal(activated.statusCode,200,activated.body);const scheduledAt=activated.json().nextCheckAt;
  const runNow=await app.inject({method:'POST',url:`${base}/${natural.json().id}/run`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:activated.json().revision}});assert.equal(runNow.statusCode,200,runNow.body);assert.equal(runNow.json().result.answer,'Synthetic headline');const afterRun=(await app.inject({method:'GET',url:base,headers:{cookie:`samvev_session=${admin.token}`}})).json().tasks.find((task:any)=>task.id===natural.json().id);assert.equal(afterRun.nextCheckAt,scheduledAt);assert.equal(afterRun.latestResult.resultKind,'answer');assert.equal(afterRun.latestResult.result.answer,'Synthetic headline');assert.equal(afterRun.latestResult.sourceUrl,'https://example.com/');assert.ok(afterRun.latestResult.checkedAt);assert.equal('provider' in afterRun.latestResult,false);assert.equal('model' in afterRun.latestResult,false);
  const productionResultAt=afterRun.latestResult.checkedAt;const smarter=await app.inject({method:'POST',url:`${base}/${natural.json().id}/smarter`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:afterRun.revision}});assert.equal(smarter.statusCode,200,smarter.body);assert.equal(smarter.json().result.answer,'Synthetic headline');const afterSmarter=(await app.inject({method:'GET',url:base,headers:{cookie:`samvev_session=${admin.token}`}})).json().tasks.find((task:any)=>task.id===natural.json().id);assert.equal(afterSmarter.nextCheckAt,scheduledAt);assert.equal(afterSmarter.modelTier,'routine');assert.equal(afterSmarter.latestResult.checkedAt,productionResultAt);
  const quality=await app.inject({method:'POST',url:`${base}/${natural.json().id}/quality`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:afterSmarter.revision,quality:'smarter'}});assert.equal(quality.statusCode,200,quality.body);assert.equal(quality.json().modelTier,'strong');assert.equal(quality.json().state,'active');assert.equal(quality.json().approvedRevision,quality.json().revision);assert.equal(quality.json().nextCheckAt,scheduledAt);

  const revised=await app.inject({method:'PATCH',url:`${base}/${natural.json().id}`,headers:auth(admin.token,admin.csrf),payload:{name:'Revised headline task',expectedRevision:quality.json().revision}});assert.equal(revised.statusCode,200,revised.body);assert.equal(revised.json().latestResult,null);assert.deepEqual(revised.json().events,[]);assert.equal(revised.json().lastResult,null);assert.equal(revised.json().lastCheckedAt,null);assert.equal(revised.json().source.finalUrl,null);
  const revisedRule=await app.inject({method:'POST',url:`${base}/${natural.json().id}/interpret`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:revised.json().revision}});assert.equal(revisedRule.statusCode,200,revisedRule.body);assert.equal(revisedRule.json().latestResult,null);const reapproved=await app.inject({method:'POST',url:`${base}/${natural.json().id}/approve`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:revisedRule.json().revision}});assert.equal(reapproved.statusCode,200,reapproved.body);assert.equal(reapproved.json().latestResult,null);assert.deepEqual(reapproved.json().events,[]);
  const callsBeforeActorGrantRace=aiCalls;beforeProviderResponse=async()=>{await pool.query('DELETE FROM membership_display_grants WHERE membership_id=$1',[narrowed.membershipId]);};const actorGrantRace=await app.inject({method:'POST',url:`${base}/${natural.json().id}/run`,headers:auth(narrowed.token,narrowed.csrf),payload:{expectedRevision:reapproved.json().revision}});assert.equal(actorGrantRace.statusCode,409,actorGrantRace.body);assert.equal(aiCalls,callsBeforeActorGrantRace+1);const afterActorGrantRace=(await app.inject({method:'GET',url:base,headers:{cookie:`samvev_session=${admin.token}`}})).json().tasks.find((task:any)=>task.id===natural.json().id);assert.equal(afterActorGrantRace.state,'active');assert.equal(afterActorGrantRace.latestResult,null);await pool.query('INSERT INTO membership_display_grants(household_id,membership_id,display_id) VALUES($1,$2,$3)',[householdId,narrowed.membershipId,displayId]);
  failProvider=true;const failedFirstRun=await app.inject({method:'POST',url:`${base}/${natural.json().id}/run`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:reapproved.json().revision}});assert.equal(failedFirstRun.statusCode,502,failedFirstRun.body);const afterFailedFirstRun=(await app.inject({method:'GET',url:base,headers:{cookie:`samvev_session=${admin.token}`}})).json().tasks.find((task:any)=>task.id===natural.json().id);assert.equal(afterFailedFirstRun.latestResult,null);assert.equal(afterFailedFirstRun.lastChangedAt,null);failProvider=false;const recoveredRun=await app.inject({method:'POST',url:`${base}/${natural.json().id}/run`,headers:auth(admin.token,admin.csrf),payload:{expectedRevision:reapproved.json().revision}});assert.equal(recoveredRun.statusCode,200,recoveredRun.body);const afterRecoveredRun=(await app.inject({method:'GET',url:base,headers:{cookie:`samvev_session=${admin.token}`}})).json().tasks.find((task:any)=>task.id===natural.json().id);assert.equal(afterRecoveredRun.latestResult.result.answer,'Synthetic headline');assert.ok(afterRecoveredRun.lastChangedAt);
  const callsBeforeDemotedOwnerRun=aiCalls;await pool.query('UPDATE memberships SET capabilities=$2 WHERE id=$1',[admin.membershipId,JSON.stringify(['household.manage'])]);const deniedOwnerRun=await app.inject({method:'POST',url:`${base}/${natural.json().id}/run`,headers:auth(narrowed.token,narrowed.csrf),payload:{expectedRevision:reapproved.json().revision}});assert.equal(deniedOwnerRun.statusCode,403,deniedOwnerRun.body);assert.equal(deniedOwnerRun.json().error.code,'MONITOR_OWNER_UNAUTHORIZED');assert.equal(aiCalls,callsBeforeDemotedOwnerRun);assert.equal((await pool.query('SELECT state FROM monitor_tasks WHERE id=$1',[natural.json().id])).rows[0].state,'paused');const afterLaterFailure=(await app.inject({method:'GET',url:base,headers:{cookie:`samvev_session=${admin.token}`}})).json().tasks.find((task:any)=>task.id===natural.json().id);assert.equal(afterLaterFailure.latestResult.result.answer,'Synthetic headline');assert.equal((await pool.query('SELECT count(*)::int AS n FROM messages WHERE id IN (SELECT message_id FROM monitor_events WHERE task_id=$1) AND state IN (\'scheduled\',\'published\')',[natural.json().id])).rows[0].n,0);

  const aiSettings=(await ai.settings(householdId)) as any;await ai.updateSettings(householdId,{provider:'openai_compatible',apiKey:null,baseUrl:'http://127.0.0.1:11434/v1',defaultModel:'synthetic-local',strongModel:'synthetic-local-strong',expectedRevision:aiSettings.revision});
  assert.equal((await ai.settings(householdId) as any).availability.status,'not_tested');
  const keyless=await ai.executeTask(householdId,{operation:'generate',purpose:'keyless_contract_test',input:'Synthetic input',modelTier:'routine',sources:[]});assert.ok(keyless.output);
});
